resource "routeros_interface_bridge" "bridge_example" {
  # router = "my-router"  # which router to target; omit for the default
  comment  = "managed by terraform"
  disabled = false

  # Optional attributes (uncomment as needed):
  # add_dhcp_option_82 = false
  # admin_mac = "replace-me"
  # admin_mac_address = "10.99.0.0/24"
  # ageing_time = "300"
  # arp = "enabled"
  # arp_timeout = "1h"
  # auto_mac = false
  # dhcp_snooping = false
  # dumb = "replace-me"
  # ether_type = "0x8100"
  # fast_forward = true
  # forward_delay = "15"
  # forward_reserved = false
  # fp_tx_rx_packet_rate = "replace-me"
  # fp_tx_rx_rate = "replace-me"
  # frame_types = "admit-all"
  # heartbeat = "5"
  # igmp = "replace-me"
  # igmp_snooping = false
  # igmp_version = "2"
  # ingress_filtering = true
  # last_member_interval = "100"
  # last_member_query_count = 2
  # max_hops = 20
  # max_learned_entries = "unlimited"
  # max_message_age = "20"
  # membership_interval = "26000"
  # mlag_heartbeat = "1h"
  # mlag_peer_port = "443"
  # mlag_priority = 0
  # mld_version = "1"
  # mstp = "replace-me"
  # mtu = 0
  # multicast_querier = false
  # multicast_router = "temporary-query"
  # mvrp = false
  # name = "tf-example"
  # peer_port = "443"
  # port_cost_mode = "long"
  # priority = 32768
  # protocol_mode = "rstp"
  # pvid = 0
  # querier_interval = "25500"
  # query_interval = "12500"
  # query_response_interval = "1000"
  # ra_guard = false
  # region_name = "replace-me"
  # region_revision = 0
  # startup_query_count = 2
  # startup_query_interval = "3125"
  # status = 0
  # transmit_hold_count = 6
  # tx_rx_packet_rate = "replace-me"
  # tx_rx_rate = "replace-me"
  # type = "replace-me"
  # vlan = "replace-me"
  # vlan_filtering = false
}
