resource "routeros_interface_wifi_security" "security_example" {
  # router = "my-router"  # which router to target; omit for the default
  name = "tf-example"

  comment  = "managed by terraform"
  disabled = false

  # Optional attributes (uncomment as needed):
  # beacon_protection = "replace-me"
  # ciphers = "tkip"
  # connect_group = "replace-me"
  # connect_priority = "replace-me"
  # dh_groups = "replace-me"
  # disable_pmkid = "replace-me"
  # eap_accounting = "replace-me"
  # eap_anonymous_identity = "replace-me"
  # eap_certificate_mode = "replace-me"
  # eap_methods = "replace-me"
  # eap_password = "REDACTED"
  # eap_tls_certificate = "replace-me"
  # eap_username = "replace-me"
  # encryption = "replace-me"
  # ft_enabled = "replace-me"
  # ft_mobility_domain = "replace-me"
  # ft_nas_identifier = "replace-me"
  # ft_over_ds = "replace-me"
  # ft_preserve_vlan_id = "replace-me"
  # ft_r0_key_lifetime = "replace-me"
  # ft_reassoc_deadline = "replace-me"
  # group_encryption = "replace-me"
  # group_key_update = "replace-me"
  # management_encryption = "replace-me"
  # management_protection = "replace-me"
  # multi_passphrase_group = "replace-me"
  # owe_transition_interface = "replace-me"
  # passphrase = "replace-me"
  # sae_anti_clogging_threshold = "replace-me"
  # sae_max_failure_rate = "replace-me"
  # sae_pwe = "replace-me"
  # types = "wpa-psk"
  # wps = "replace-me"
}
