resource "routeros_routing_bgp_template" "template_example" {
  # router = "my-router"  # which router to target; omit for the default
  name = "tf-example"

  comment  = "managed by terraform"
  disabled = false

  # Optional attributes (uncomment as needed):
  # afi = "replace-me"
  # allow_as_in = "replace-me"
  # as = "65000"
  # as_override = "replace-me"
  # cisco_vpls_nlri_length_format = "replace-me"
  # cluster_id = "replace-me"
  # default_originate = "replace-me"
  # default_prepend = "replace-me"
  # hold_time = "replace-me"
  # ignore_as_path_length = "replace-me"
  # input_accept_communities = "replace-me"
  # input_accept_ext_communities = "replace-me"
  # input_accept_large_communities = "replace-me"
  # input_accept_nlri = "replace-me"
  # input_affinity = "replace-me"
  # input_filter = "replace-me"
  # input_filter_communities = "replace-me"
  # input_filter_ext_communities = "replace-me"
  # input_filter_large_communities = "replace-me"
  # input_filter_unknown = "replace-me"
  # keep_sent_attributes = "replace-me"
  # keepalive_time = "replace-me"
  # multihop = "replace-me"
  # nexthop_choice = "replace-me"
  # no_client_to_client_reflection = "replace-me"
  # no_early_cut = "replace-me"
  # output_affinity = "replace-me"
  # output_filter = "replace-me"
  # output_network = "replace-me"
  # output_redistribute = "replace-me"
  # output_selection_policy = "replace-me"
  # remove_private_as = "replace-me"
  # router_id = "1.1.1.1"
  # routing_table = "main"
  # templates = "replace-me"
  # use_bfd = "replace-me"
  # vrf = "main"
}
