resource "routeros_interface_ethernet" "ethernet_example" {
  # router = "my-router"  # which router to target; omit for the default
  comment  = "managed by terraform"
  disabled = false

  # Optional attributes (uncomment as needed):
  # advertise = []
  # arp = "disabled"
  # arp_timeout = "1h"
  # autoneg = false
  # blink = "replace-me"
  # cable_settings = "replace-me"
  # cable_test = "replace-me"
  # combo_mode = "auto"
  # disable_running_check = false
  # disable_time = "300"
  # extrastats = "replace-me"
  # fec_mode = "off"
  # flowcntrl = "replace-me"
  # ignore_rx_los = false
  # l2_mtu = 0
  # loop_protect = "default"
  # loop_protect_disable_time = "1h"
  # loop_protect_send_interval = "1h"
  # mac_address = "10.99.0.0/24"
  # mtu = 1500
  # name = "tf-example"
  # noautoneg = "replace-me"
  # non_mgmt = "replace-me"
  # orig_mac_address = "10.99.0.0/24"
  # passthrough_interface = "replace-me"
  # poe_out = "off"
  # poe_priority = 0
  # poe_voltage = "auto"
  # poe = "replace-me"
  # poeping = "replace-me"
  # power_cycle = "replace-me"
  # power_cycle_interval = "1h"
  # power_cycle_ping_address = "10.99.0.0/24"
  # power_cycle_ping_enabled = false
  # power_cycle_ping_timeout = "1h"
  # qstats = "replace-me"
  # rate_select = "low"
  # reset_counters = "replace-me"
  # reset_mac_address = "10.99.0.0/24"
  # rx_flow_control = "off"
  # send_interval = "5"
  # sfp = false
  # sfp_shutdown_temperature = 0
  # speed = "10m-baset-half"
  # tx_flow_control = "off"
}
