resource "routeros_tool_sniffer_stop" "stop_example" {
  # router = "my-router"  # which router to target; omit for the default

  # Optional attributes (uncomment as needed):
  # file_limit = "replace-me"
  # file_name = "replace-me"
  # filter_cpu = "replace-me"
  # filter_direction = "replace-me"
  # filter_dst_ip_address = "10.99.0.0/24"
  # filter_dst_ipv6_address = "10.99.0.0/24"
  # filter_dst_mac_address = "10.99.0.0/24"
  # filter_dst_port = "443"
  # filter_interface = "replace-me"
  # filter_ip_address = "10.99.0.0/24"
  # filter_ip_protocol = "replace-me"
  # filter_ipv6_address = "10.99.0.0/24"
  # filter_mac_address = "10.99.0.0/24"
  # filter_mac_protocol = "replace-me"
  # filter_operator_between_entries = "replace-me"
  # filter_port = "443"
  # filter_size = "replace-me"
  # filter_src_ip_address = "10.99.0.0/24"
  # filter_src_ipv6_address = "10.99.0.0/24"
  # filter_src_mac_address = "10.99.0.0/24"
  # filter_src_port = "443"
  # filter_stream = "replace-me"
  # filter_vlan = "replace-me"
  # memory_limit = "replace-me"
  # memory_scroll = "replace-me"
  # only_headers = "replace-me"
  # show_frame = "replace-me"
  # streaming_enabled = "replace-me"
  # streaming_port = "443"
  # streaming_server = "replace-me"
}
