resource "routeros_tool_traffic_generator_packet_template" "packet_template_example" {
  # router = "my-router"  # which router to target; omit for the default
  comment = "managed by terraform"

  # Optional attributes (uncomment as needed):
  # data = "uninitialized"
  # data_byte = 0
  # dscp_ecn = "replace-me"
  # dst = "replace-me"
  # dst_port = "443"
  # flow_label = "replace-me"
  # frag_offset = "replace-me"
  # gateway = "replace-me"
  # header = "replace-me"
  # header_stack = "replace-me"
  # hop_limit = "replace-me"
  # interface = "ether1"
  # ip = "replace-me"
  # ip_id = "replace-me"
  # ipv6 = "replace-me"
  # mac = "replace-me"
  # name = "tf-example"
  # next_header = "replace-me"
  # port = "443"
  # priority = "replace-me"
  # protocol = "replace-me"
  # raw = "replace-me"
  # raw_packet_templates = "replace-me"
  # specbyte = "replace-me"
  # src = "replace-me"
  # src_port = "443"
  # tcp = "replace-me"
  # tcp_ack = "replace-me"
  # tcp_data_offset = "replace-me"
  # tcp_dst_port = "443"
  # tcp_flags = "replace-me"
  # tcp_src_port = "443"
  # tcp_syn = "replace-me"
  # tcp_urgent_pointer = "replace-me"
  # tcp_window_size = "replace-me"
  # traffic_class = "replace-me"
  # ttl = "replace-me"
  # udp = "replace-me"
  # vlan = "replace-me"
  # vlan_id = "replace-me"
}
