resource "routeros_ppp_profile" "profile_example" {
  # router = "my-router"  # which router to target; omit for the default
  name = "tf-example"

  comment = "managed by terraform"

  # Optional attributes (uncomment as needed):
  # address_list = "replace-me"
  # bridge = "bridge1"
  # bridge_horizon = "replace-me"
  # bridge_learning = "no"
  # bridge_path_cost = "replace-me"
  # bridge_port_priority = "replace-me"
  # bridge_port_trusted = "replace-me"
  # bridge_port_vid = "replace-me"
  # change_tcp_mss = "no"
  # dhcpv6_lease_time = "replace-me"
  # dhcpv6_pd_pool = "replace-me"
  # dhcpv6_use_radius = "replace-me"
  # dns_server = "1.1.1.1,8.8.8.8"
  # idle_timeout = "replace-me"
  # incoming_filter = "replace-me"
  # insert_queue_before = "replace-me"
  # interface_list = "replace-me"
  # local_address = "10.99.0.1"
  # on_down = "replace-me"
  # on_up = "replace-me"
  # only_one = "no"
  # outgoing_filter = "replace-me"
  # parent_queue = "replace-me"
  # remote_address = "10.99.0.1"
  # remote_ipv6_prefix_pool = "replace-me"
  # remote_ipv6_prefix_reuse = "replace-me"
  # session_timeout = "replace-me"
  # use_compression = "no"
  # use_encryption = "no"
  # use_ipv6 = "yes"
  # use_mpls = "no"
  # use_upnp = "replace-me"
  # wins_server = "replace-me"
}
