resource "routeros_disk" "disk_example" {
  # router = "my-router"  # which router to target; omit for the default
  comment  = "managed by terraform"
  disabled = false

  # Optional attributes (uncomment as needed):
  # acquired = false
  # block_device = false
  # btrfs = "replace-me"
  # eject_drive = "replace-me"
  # empty = false
  # encrypted = false
  # formatting = false
  # guid_partition_table = false
  # i_scsi_export = false
  # i_scsi_server_iqn = "replace-me"
  # i_scsi_server_port = "443"
  # iscsi_sharing = "replace-me"
  # media_interface = "replace-me"
  # media_sharing = false
  # mount_compress = false
  # mount_filesystem = true
  # mount_point_template = "replace-me"
  # mount_read_only = false
  # mounted = false
  # newfileman = "replace-me"
  # nfs_sharing = false
  # nvme = "replace-me"
  # nvme_tcp_export = false
  # nvme_tcp_server_allow_host_name = "replace-me"
  # nvme_tcp_server_nqn = "replace-me"
  # nvme_tcp_server_password = "REDACTED"
  # nvme_tcp_server_port = "443"
  # oldfileman = "replace-me"
  # parent = "4.294967295e+09"
  # part = "replace-me"
  # partition = false
  # partition_offset = "65536"
  # partition_size = "replace-me"
  # raid = "replace-me"
  # raid_and_master = "replace-me"
  # raid_and_type = "replace-me"
  # raid_master = "4.294967295e+09"
  # raid_member = false
  # raid_member_failed = false
  # raid_role = "spare"
  # raid_scrub = "replace-me"
  # read_only = false
  # reset_counters = "replace-me"
  # rose = "replace-me"
  # scan = "replace-me"
  # self_encrypted_and_locked = false
  # self_encryption_enabled = false
  # self_encryption_password = "REDACTED"
  # self_encryption_supported = false
  # slot = "replace-me"
  # smb_server_encryption = false
  # smb_server_password = "REDACTED"
  # smb_server_user = "replace-me"
  # smb_sharing = false
  # swap = false
  # swap_enabled = false
  # tmpfs = "replace-me"
  # tmpfs_max_size = "replace-me"
  # trim = "replace-me"
  # type = "6"
}
