// Code generated by gen-provider. DO NOT EDIT.
package provider

import (
	"context"
	"fmt"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/ebogdum/terraform-provider-routeros/internal/client"
	"github.com/ebogdum/terraform-provider-routeros/internal/schemautil"
)

var (
	_ resource.Resource                = &InterfaceBridgeResource{}
	_ resource.ResourceWithImportState = &InterfaceBridgeResource{}
	_                                  = attr.Value(nil)
	_                                  = strings.TrimSpace
	_                                  = path.Root
)

type InterfaceBridgeResource struct {
	reg *client.Registry
}

type InterfaceBridgeModel struct {
	ID                types.String `tfsdk:"id"`
	AdminMAC          types.String `tfsdk:"admin_mac"`
	AgeingTime        types.String `tfsdk:"ageing_time"`
	ARP               types.String `tfsdk:"arp"`
	ARPTimeout        types.String `tfsdk:"arp_timeout"`
	AutoMAC           types.Bool   `tfsdk:"auto_mac"`
	Comment           types.String `tfsdk:"comment"`
	DHCPSnooping      types.Bool   `tfsdk:"dhcp_snooping"`
	Disabled          types.Bool   `tfsdk:"disabled"`
	EtherType         types.String `tfsdk:"ether_type"`
	FastForward       types.Bool   `tfsdk:"fast_forward"`
	ForwardDelay      types.String `tfsdk:"forward_delay"`
	FrameTypes        types.String `tfsdk:"frame_types"`
	IgmpSnooping      types.Bool   `tfsdk:"igmp_snooping"`
	IngressFiltering  types.String `tfsdk:"ingress_filtering"`
	MaxLearnedEntries types.String `tfsdk:"max_learned_entries"`
	MaxMessageAge     types.String `tfsdk:"max_message_age"`
	MlagHeartbeat     types.String `tfsdk:"mlag_heartbeat"`
	MlagPeerPort      types.String `tfsdk:"mlag_peer_port"`
	MlagPriority      types.Int64  `tfsdk:"mlag_priority"`
	MTU               types.String `tfsdk:"mtu"`
	Mvrp              types.String `tfsdk:"mvrp"`
	Name              types.String `tfsdk:"name"`
	PortCostMode      types.String `tfsdk:"port_cost_mode"`
	Priority          types.Int64  `tfsdk:"priority"`
	ProtocolMode      types.String `tfsdk:"protocol_mode"`
	Pvid              types.String `tfsdk:"pvid"`
	RaGuard           types.Bool   `tfsdk:"ra_guard"`
	RegionName        types.String `tfsdk:"region_name"`
	RegionRevision    types.String `tfsdk:"region_revision"`
	TransmitHoldCount types.Int64  `tfsdk:"transmit_hold_count"`
	VLANFiltering     types.Bool   `tfsdk:"vlan_filtering"`
	Router            types.String `tfsdk:"router"`
}

func NewInterfaceBridgeResource() resource.Resource { return &InterfaceBridgeResource{} }

func (r *InterfaceBridgeResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_interface_bridge"
}

func (r *InterfaceBridgeResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	reg, diags := configureRegistry(req.ProviderData)
	resp.Diagnostics.Append(diags...)
	if reg != nil {
		r.reg = reg
	}
	_ = fmt.Sprintf
}

func (r *InterfaceBridgeResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Mirrors RouterOS `/interface/bridge`.",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Computed:      true,
				Description:   "RouterOS internal .id.",
				PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},
			"admin_mac": schema.StringAttribute{
				Optional:    true,
				Computed:    true,
				Description: "",
			},
			"ageing_time": schema.StringAttribute{
				Optional:      true,
				Computed:      true,
				Description:   "",
				Validators:    []validator.String{schemautil.IsDurationRouterOS()},
				PlanModifiers: []planmodifier.String{schemautil.NormalizeDuration()},
			},
			"arp": schema.StringAttribute{
				Optional:    true,
				Computed:    true,
				Description: "",
			},
			"arp_timeout": schema.StringAttribute{
				Optional:    true,
				Computed:    true,
				Description: "",
			},
			"auto_mac": schema.BoolAttribute{
				Optional:    true,
				Computed:    true,
				Description: "",
			},
			"comment": schema.StringAttribute{
				Optional:    true,
				Computed:    true,
				Description: "Free-form comment.",
			},
			"dhcp_snooping": schema.BoolAttribute{
				Optional:    true,
				Computed:    true,
				Description: "",
			},
			"disabled": schema.BoolAttribute{
				Optional:    true,
				Computed:    true,
				Description: "Whether the entry is disabled.",
			},
			"ether_type": schema.StringAttribute{
				Optional:    true,
				Computed:    true,
				Description: "",
			},
			"fast_forward": schema.BoolAttribute{
				Optional:    true,
				Computed:    true,
				Description: "",
			},
			"forward_delay": schema.StringAttribute{
				Optional:      true,
				Computed:      true,
				Description:   "",
				Validators:    []validator.String{schemautil.IsDurationRouterOS()},
				PlanModifiers: []planmodifier.String{schemautil.NormalizeDuration()},
			},
			"frame_types": schema.StringAttribute{
				Optional:    true,
				Computed:    true,
				Description: "",
			},
			"igmp_snooping": schema.BoolAttribute{
				Optional:    true,
				Computed:    true,
				Description: "",
			},
			"ingress_filtering": schema.StringAttribute{
				Optional:    true,
				Computed:    true,
				Description: "",
			},
			"max_learned_entries": schema.StringAttribute{
				Optional:    true,
				Computed:    true,
				Description: "",
			},
			"max_message_age": schema.StringAttribute{
				Optional:      true,
				Computed:      true,
				Description:   "",
				Validators:    []validator.String{schemautil.IsDurationRouterOS()},
				PlanModifiers: []planmodifier.String{schemautil.NormalizeDuration()},
			},
			"mlag_heartbeat": schema.StringAttribute{
				Optional:      true,
				Computed:      true,
				Description:   "",
				Validators:    []validator.String{schemautil.IsDurationRouterOS()},
				PlanModifiers: []planmodifier.String{schemautil.NormalizeDuration()},
			},
			"mlag_peer_port": schema.StringAttribute{
				Optional:    true,
				Computed:    true,
				Description: "",
			},
			"mlag_priority": schema.Int64Attribute{
				Optional:    true,
				Computed:    true,
				Description: "",
			},
			"mtu": schema.StringAttribute{
				Optional:    true,
				Computed:    true,
				Description: "",
			},
			"mvrp": schema.StringAttribute{
				Optional:    true,
				Computed:    true,
				Description: "",
			},
			"name": schema.StringAttribute{
				Optional:    true,
				Computed:    true,
				Description: "",
			},
			"port_cost_mode": schema.StringAttribute{
				Optional:    true,
				Computed:    true,
				Description: "",
			},
			"priority": schema.Int64Attribute{
				Optional:    true,
				Computed:    true,
				Description: "",
			},
			"protocol_mode": schema.StringAttribute{
				Optional:    true,
				Computed:    true,
				Description: "",
			},
			"pvid": schema.StringAttribute{
				Optional:    true,
				Computed:    true,
				Description: "",
			},
			"ra_guard": schema.BoolAttribute{
				Optional:    true,
				Computed:    true,
				Description: "",
			},
			"region_name": schema.StringAttribute{
				Optional:    true,
				Computed:    true,
				Description: "",
			},
			"region_revision": schema.StringAttribute{
				Optional:    true,
				Computed:    true,
				Description: "",
			},
			"transmit_hold_count": schema.Int64Attribute{
				Optional:    true,
				Computed:    true,
				Description: "",
			},
			"vlan_filtering": schema.BoolAttribute{
				Optional:    true,
				Computed:    true,
				Description: "",
			},
			"router": schema.StringAttribute{
				Optional:    true,
				Description: "Name of the router (key in provider's `routers` map). Omit to use the default.",
			},
		},
	}
}

func (r *InterfaceBridgeResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan InterfaceBridgeModel
	if diags := req.Plan.Get(ctx, &plan); diags.HasError() {
		resp.Diagnostics.Append(diags...)
		return
	}
	c := pickClient(r.reg, plan.Router, &resp.Diagnostics)
	if c == nil {
		return
	}
	body := client.Object{}
	if !(plan.AdminMAC.IsNull() || plan.AdminMAC.IsUnknown()) {
		body["admin-mac"] = plan.AdminMAC.ValueString()
	}
	if !(plan.AgeingTime.IsNull() || plan.AgeingTime.IsUnknown()) {
		body["ageing-time"] = plan.AgeingTime.ValueString()
	}
	if !(plan.ARP.IsNull() || plan.ARP.IsUnknown()) {
		body["arp"] = plan.ARP.ValueString()
	}
	if !(plan.ARPTimeout.IsNull() || plan.ARPTimeout.IsUnknown()) {
		body["arp-timeout"] = plan.ARPTimeout.ValueString()
	}
	if !(plan.AutoMAC.IsNull() || plan.AutoMAC.IsUnknown()) {
		body["auto-mac"] = client.FormatBool(plan.AutoMAC.ValueBool())
	}
	if !(plan.Comment.IsNull() || plan.Comment.IsUnknown()) {
		body["comment"] = plan.Comment.ValueString()
	}
	if !(plan.DHCPSnooping.IsNull() || plan.DHCPSnooping.IsUnknown()) {
		body["dhcp-snooping"] = client.FormatBool(plan.DHCPSnooping.ValueBool())
	}
	if !(plan.Disabled.IsNull() || plan.Disabled.IsUnknown()) {
		body["disabled"] = client.FormatBool(plan.Disabled.ValueBool())
	}
	if !(plan.EtherType.IsNull() || plan.EtherType.IsUnknown()) {
		body["ether-type"] = plan.EtherType.ValueString()
	}
	if !(plan.FastForward.IsNull() || plan.FastForward.IsUnknown()) {
		body["fast-forward"] = client.FormatBool(plan.FastForward.ValueBool())
	}
	if !(plan.ForwardDelay.IsNull() || plan.ForwardDelay.IsUnknown()) {
		body["forward-delay"] = plan.ForwardDelay.ValueString()
	}
	if !(plan.FrameTypes.IsNull() || plan.FrameTypes.IsUnknown()) {
		body["frame-types"] = plan.FrameTypes.ValueString()
	}
	if !(plan.IgmpSnooping.IsNull() || plan.IgmpSnooping.IsUnknown()) {
		body["igmp-snooping"] = client.FormatBool(plan.IgmpSnooping.ValueBool())
	}
	if !(plan.IngressFiltering.IsNull() || plan.IngressFiltering.IsUnknown()) {
		body["ingress-filtering"] = plan.IngressFiltering.ValueString()
	}
	if !(plan.MaxLearnedEntries.IsNull() || plan.MaxLearnedEntries.IsUnknown()) {
		body["max-learned-entries"] = plan.MaxLearnedEntries.ValueString()
	}
	if !(plan.MaxMessageAge.IsNull() || plan.MaxMessageAge.IsUnknown()) {
		body["max-message-age"] = plan.MaxMessageAge.ValueString()
	}
	if !(plan.MlagHeartbeat.IsNull() || plan.MlagHeartbeat.IsUnknown()) {
		body["mlag-heartbeat"] = plan.MlagHeartbeat.ValueString()
	}
	if !(plan.MlagPeerPort.IsNull() || plan.MlagPeerPort.IsUnknown()) {
		body["mlag-peer-port"] = plan.MlagPeerPort.ValueString()
	}
	if !(plan.MlagPriority.IsNull() || plan.MlagPriority.IsUnknown()) {
		body["mlag-priority"] = client.FormatInt64(plan.MlagPriority.ValueInt64())
	}
	if !(plan.MTU.IsNull() || plan.MTU.IsUnknown()) {
		body["mtu"] = plan.MTU.ValueString()
	}
	if !(plan.Mvrp.IsNull() || plan.Mvrp.IsUnknown()) {
		body["mvrp"] = plan.Mvrp.ValueString()
	}
	if !(plan.Name.IsNull() || plan.Name.IsUnknown()) {
		body["name"] = plan.Name.ValueString()
	}
	if !(plan.PortCostMode.IsNull() || plan.PortCostMode.IsUnknown()) {
		body["port-cost-mode"] = plan.PortCostMode.ValueString()
	}
	if !(plan.Priority.IsNull() || plan.Priority.IsUnknown()) {
		body["priority"] = client.FormatInt64(plan.Priority.ValueInt64())
	}
	if !(plan.ProtocolMode.IsNull() || plan.ProtocolMode.IsUnknown()) {
		body["protocol-mode"] = plan.ProtocolMode.ValueString()
	}
	if !(plan.Pvid.IsNull() || plan.Pvid.IsUnknown()) {
		body["pvid"] = plan.Pvid.ValueString()
	}
	if !(plan.RaGuard.IsNull() || plan.RaGuard.IsUnknown()) {
		body["ra-guard"] = client.FormatBool(plan.RaGuard.ValueBool())
	}
	if !(plan.RegionName.IsNull() || plan.RegionName.IsUnknown()) {
		body["region-name"] = plan.RegionName.ValueString()
	}
	if !(plan.RegionRevision.IsNull() || plan.RegionRevision.IsUnknown()) {
		body["region-revision"] = plan.RegionRevision.ValueString()
	}
	if !(plan.TransmitHoldCount.IsNull() || plan.TransmitHoldCount.IsUnknown()) {
		body["transmit-hold-count"] = client.FormatInt64(plan.TransmitHoldCount.ValueInt64())
	}
	if !(plan.VLANFiltering.IsNull() || plan.VLANFiltering.IsUnknown()) {
		body["vlan-filtering"] = client.FormatBool(plan.VLANFiltering.ValueBool())
	}
	obj, err := c.Add(ctx, "/interface/bridge", body)
	if err != nil {
		resp.Diagnostics.AddError("Create /interface/bridge failed", err.Error())
		return
	}
	interfaceBridgeApply(ctx, obj, &plan)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *InterfaceBridgeResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state InterfaceBridgeModel
	if diags := req.State.Get(ctx, &state); diags.HasError() {
		resp.Diagnostics.Append(diags...)
		return
	}
	c := pickClient(r.reg, state.Router, &resp.Diagnostics)
	if c == nil {
		return
	}
	obj, err := c.GetByID(ctx, "/interface/bridge", state.ID.ValueString())
	if err != nil {
		if client.IsNotFound(err) {
			resp.State.RemoveResource(ctx)
			return
		}
		resp.Diagnostics.AddError("Read /interface/bridge failed", err.Error())
		return
	}
	interfaceBridgeApply(ctx, obj, &state)
	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *InterfaceBridgeResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan, state InterfaceBridgeModel
	if diags := req.Plan.Get(ctx, &plan); diags.HasError() {
		resp.Diagnostics.Append(diags...)
		return
	}
	if diags := req.State.Get(ctx, &state); diags.HasError() {
		resp.Diagnostics.Append(diags...)
		return
	}
	c := pickClient(r.reg, plan.Router, &resp.Diagnostics)
	if c == nil {
		return
	}
	body := client.Object{}
	if !plan.AdminMAC.Equal(state.AdminMAC) {
		body["admin-mac"] = plan.AdminMAC.ValueString()
	}
	if !plan.AgeingTime.Equal(state.AgeingTime) {
		body["ageing-time"] = plan.AgeingTime.ValueString()
	}
	if !plan.ARP.Equal(state.ARP) {
		body["arp"] = plan.ARP.ValueString()
	}
	if !plan.ARPTimeout.Equal(state.ARPTimeout) {
		body["arp-timeout"] = plan.ARPTimeout.ValueString()
	}
	if !plan.AutoMAC.Equal(state.AutoMAC) {
		body["auto-mac"] = client.FormatBool(plan.AutoMAC.ValueBool())
	}
	if !plan.Comment.Equal(state.Comment) {
		body["comment"] = plan.Comment.ValueString()
	}
	if !plan.DHCPSnooping.Equal(state.DHCPSnooping) {
		body["dhcp-snooping"] = client.FormatBool(plan.DHCPSnooping.ValueBool())
	}
	if !plan.Disabled.Equal(state.Disabled) {
		body["disabled"] = client.FormatBool(plan.Disabled.ValueBool())
	}
	if !plan.EtherType.Equal(state.EtherType) {
		body["ether-type"] = plan.EtherType.ValueString()
	}
	if !plan.FastForward.Equal(state.FastForward) {
		body["fast-forward"] = client.FormatBool(plan.FastForward.ValueBool())
	}
	if !plan.ForwardDelay.Equal(state.ForwardDelay) {
		body["forward-delay"] = plan.ForwardDelay.ValueString()
	}
	if !plan.FrameTypes.Equal(state.FrameTypes) {
		body["frame-types"] = plan.FrameTypes.ValueString()
	}
	if !plan.IgmpSnooping.Equal(state.IgmpSnooping) {
		body["igmp-snooping"] = client.FormatBool(plan.IgmpSnooping.ValueBool())
	}
	if !plan.IngressFiltering.Equal(state.IngressFiltering) {
		body["ingress-filtering"] = plan.IngressFiltering.ValueString()
	}
	if !plan.MaxLearnedEntries.Equal(state.MaxLearnedEntries) {
		body["max-learned-entries"] = plan.MaxLearnedEntries.ValueString()
	}
	if !plan.MaxMessageAge.Equal(state.MaxMessageAge) {
		body["max-message-age"] = plan.MaxMessageAge.ValueString()
	}
	if !plan.MlagHeartbeat.Equal(state.MlagHeartbeat) {
		body["mlag-heartbeat"] = plan.MlagHeartbeat.ValueString()
	}
	if !plan.MlagPeerPort.Equal(state.MlagPeerPort) {
		body["mlag-peer-port"] = plan.MlagPeerPort.ValueString()
	}
	if !plan.MlagPriority.Equal(state.MlagPriority) {
		body["mlag-priority"] = client.FormatInt64(plan.MlagPriority.ValueInt64())
	}
	if !plan.MTU.Equal(state.MTU) {
		body["mtu"] = plan.MTU.ValueString()
	}
	if !plan.Mvrp.Equal(state.Mvrp) {
		body["mvrp"] = plan.Mvrp.ValueString()
	}
	if !plan.Name.Equal(state.Name) {
		body["name"] = plan.Name.ValueString()
	}
	if !plan.PortCostMode.Equal(state.PortCostMode) {
		body["port-cost-mode"] = plan.PortCostMode.ValueString()
	}
	if !plan.Priority.Equal(state.Priority) {
		body["priority"] = client.FormatInt64(plan.Priority.ValueInt64())
	}
	if !plan.ProtocolMode.Equal(state.ProtocolMode) {
		body["protocol-mode"] = plan.ProtocolMode.ValueString()
	}
	if !plan.Pvid.Equal(state.Pvid) {
		body["pvid"] = plan.Pvid.ValueString()
	}
	if !plan.RaGuard.Equal(state.RaGuard) {
		body["ra-guard"] = client.FormatBool(plan.RaGuard.ValueBool())
	}
	if !plan.RegionName.Equal(state.RegionName) {
		body["region-name"] = plan.RegionName.ValueString()
	}
	if !plan.RegionRevision.Equal(state.RegionRevision) {
		body["region-revision"] = plan.RegionRevision.ValueString()
	}
	if !plan.TransmitHoldCount.Equal(state.TransmitHoldCount) {
		body["transmit-hold-count"] = client.FormatInt64(plan.TransmitHoldCount.ValueInt64())
	}
	if !plan.VLANFiltering.Equal(state.VLANFiltering) {
		body["vlan-filtering"] = client.FormatBool(plan.VLANFiltering.ValueBool())
	}
	if len(body) > 0 {
		obj, err := c.Set(ctx, "/interface/bridge", state.ID.ValueString(), body)
		if err != nil {
			resp.Diagnostics.AddError("Update /interface/bridge failed", err.Error())
			return
		}
		interfaceBridgeApply(ctx, obj, &plan)
	} else {
		plan.ID = state.ID
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *InterfaceBridgeResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state InterfaceBridgeModel
	if diags := req.State.Get(ctx, &state); diags.HasError() {
		resp.Diagnostics.Append(diags...)
		return
	}
	c := pickClient(r.reg, state.Router, &resp.Diagnostics)
	if c == nil {
		return
	}
	if err := c.Remove(ctx, "/interface/bridge", state.ID.ValueString()); err != nil {
		resp.Diagnostics.AddError("Delete /interface/bridge failed", err.Error())
	}
}

func (r *InterfaceBridgeResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	// Import formats accepted:
	//   *<id>                            -> bare RouterOS .id on the default router
	//   <router>/*<id>                   -> .id on the named router
	//   <router>/<naturalkey>            -> resolved via List + filter
	//   <naturalkey>                     -> resolved on the default router
	id := req.ID
	routerName := ""
	if i := strings.Index(id, "/"); i > 0 && !strings.HasPrefix(id, "*") {
		routerName, id = id[:i], id[i+1:]
	}
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("router"), types.StringValue(routerName))...)
	if strings.HasPrefix(id, "*") {
		resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("id"), types.StringValue(id))...)
		return
	}
	c := pickClient(r.reg, types.StringValue(routerName), &resp.Diagnostics)
	if c == nil {
		return
	}
	rows, err := interfaceBridgeLookupByNaturalKey(ctx, c, id)
	if err != nil {
		resp.Diagnostics.AddError("Import lookup failed", err.Error())
		return
	}
	if len(rows) == 0 {
		resp.Diagnostics.AddError("Import not found", fmt.Sprintf("no /interface/bridge matches %q", id))
		return
	}
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("id"), types.StringValue(rows[0][".id"]))...)
}

// interfaceBridgeLookupByNaturalKey searches for a record whose natural
// keys match id. The strategy: try every key declared in the schema overlay's
// natural_keys list (or fall back to "name") with equality matching.
func interfaceBridgeLookupByNaturalKey(ctx context.Context, c *client.Client, id string) ([]client.Object, error) {
	keys := []string{}
	if len(keys) == 0 {
		keys = []string{"name"}
	}
	for _, k := range keys {
		rows, err := c.List(ctx, "/interface/bridge", client.WithFilter(k, id))
		if err != nil {
			return nil, err
		}
		if len(rows) > 0 {
			return rows, nil
		}
	}
	return nil, nil
}

func interfaceBridgeApply(ctx context.Context, obj client.Object, m *InterfaceBridgeModel) {
	_ = ctx
	m.ID = types.StringValue(obj[".id"])
	if v, ok := obj["admin-mac"]; ok {
		_ = v
		if v != "" {
			m.AdminMAC = types.StringValue(v)
		} else {
			m.AdminMAC = types.StringNull()
		}
	} else {
		m.AdminMAC = types.StringNull()
	}
	if v, ok := obj["ageing-time"]; ok {
		_ = v
		if v != "" {
			m.AgeingTime = types.StringValue(v)
		} else {
			m.AgeingTime = types.StringNull()
		}
	} else {
		m.AgeingTime = types.StringNull()
	}
	if v, ok := obj["arp"]; ok {
		_ = v
		if v != "" {
			m.ARP = types.StringValue(v)
		} else {
			m.ARP = types.StringNull()
		}
	} else {
		m.ARP = types.StringNull()
	}
	if v, ok := obj["arp-timeout"]; ok {
		_ = v
		if v != "" {
			m.ARPTimeout = types.StringValue(v)
		} else {
			m.ARPTimeout = types.StringNull()
		}
	} else {
		m.ARPTimeout = types.StringNull()
	}
	if v, ok := obj["auto-mac"]; ok {
		_ = v
		if b, err := client.ParseBool(v); err == nil {
			m.AutoMAC = types.BoolValue(b)
		} else {
			m.AutoMAC = types.BoolNull()
		}
	} else {
		m.AutoMAC = types.BoolNull()
	}
	if v, ok := obj["comment"]; ok {
		_ = v
		if v != "" {
			m.Comment = types.StringValue(v)
		} else {
			m.Comment = types.StringNull()
		}
	} else {
		m.Comment = types.StringNull()
	}
	if v, ok := obj["dhcp-snooping"]; ok {
		_ = v
		if b, err := client.ParseBool(v); err == nil {
			m.DHCPSnooping = types.BoolValue(b)
		} else {
			m.DHCPSnooping = types.BoolNull()
		}
	} else {
		m.DHCPSnooping = types.BoolNull()
	}
	if v, ok := obj["disabled"]; ok {
		_ = v
		if b, err := client.ParseBool(v); err == nil {
			m.Disabled = types.BoolValue(b)
		} else {
			m.Disabled = types.BoolNull()
		}
	} else {
		m.Disabled = types.BoolNull()
	}
	if v, ok := obj["ether-type"]; ok {
		_ = v
		if v != "" {
			m.EtherType = types.StringValue(v)
		} else {
			m.EtherType = types.StringNull()
		}
	} else {
		m.EtherType = types.StringNull()
	}
	if v, ok := obj["fast-forward"]; ok {
		_ = v
		if b, err := client.ParseBool(v); err == nil {
			m.FastForward = types.BoolValue(b)
		} else {
			m.FastForward = types.BoolNull()
		}
	} else {
		m.FastForward = types.BoolNull()
	}
	if v, ok := obj["forward-delay"]; ok {
		_ = v
		if v != "" {
			m.ForwardDelay = types.StringValue(v)
		} else {
			m.ForwardDelay = types.StringNull()
		}
	} else {
		m.ForwardDelay = types.StringNull()
	}
	if v, ok := obj["frame-types"]; ok {
		_ = v
		if v != "" {
			m.FrameTypes = types.StringValue(v)
		} else {
			m.FrameTypes = types.StringNull()
		}
	} else {
		m.FrameTypes = types.StringNull()
	}
	if v, ok := obj["igmp-snooping"]; ok {
		_ = v
		if b, err := client.ParseBool(v); err == nil {
			m.IgmpSnooping = types.BoolValue(b)
		} else {
			m.IgmpSnooping = types.BoolNull()
		}
	} else {
		m.IgmpSnooping = types.BoolNull()
	}
	if v, ok := obj["ingress-filtering"]; ok {
		_ = v
		if v != "" {
			m.IngressFiltering = types.StringValue(v)
		} else {
			m.IngressFiltering = types.StringNull()
		}
	} else {
		m.IngressFiltering = types.StringNull()
	}
	if v, ok := obj["max-learned-entries"]; ok {
		_ = v
		if v != "" {
			m.MaxLearnedEntries = types.StringValue(v)
		} else {
			m.MaxLearnedEntries = types.StringNull()
		}
	} else {
		m.MaxLearnedEntries = types.StringNull()
	}
	if v, ok := obj["max-message-age"]; ok {
		_ = v
		if v != "" {
			m.MaxMessageAge = types.StringValue(v)
		} else {
			m.MaxMessageAge = types.StringNull()
		}
	} else {
		m.MaxMessageAge = types.StringNull()
	}
	if v, ok := obj["mlag-heartbeat"]; ok {
		_ = v
		if v != "" {
			m.MlagHeartbeat = types.StringValue(v)
		} else {
			m.MlagHeartbeat = types.StringNull()
		}
	} else {
		m.MlagHeartbeat = types.StringNull()
	}
	if v, ok := obj["mlag-peer-port"]; ok {
		_ = v
		if v != "" {
			m.MlagPeerPort = types.StringValue(v)
		} else {
			m.MlagPeerPort = types.StringNull()
		}
	} else {
		m.MlagPeerPort = types.StringNull()
	}
	if v, ok := obj["mlag-priority"]; ok {
		_ = v
		if n, err := client.ParseInt64(v); err == nil {
			m.MlagPriority = types.Int64Value(n)
		} else {
			m.MlagPriority = types.Int64Null()
		}
	} else {
		m.MlagPriority = types.Int64Null()
	}
	if v, ok := obj["mtu"]; ok {
		_ = v
		if v != "" {
			m.MTU = types.StringValue(v)
		} else {
			m.MTU = types.StringNull()
		}
	} else {
		m.MTU = types.StringNull()
	}
	if v, ok := obj["mvrp"]; ok {
		_ = v
		if v != "" {
			m.Mvrp = types.StringValue(v)
		} else {
			m.Mvrp = types.StringNull()
		}
	} else {
		m.Mvrp = types.StringNull()
	}
	if v, ok := obj["name"]; ok {
		_ = v
		if v != "" {
			m.Name = types.StringValue(v)
		} else {
			m.Name = types.StringNull()
		}
	} else {
		m.Name = types.StringNull()
	}
	if v, ok := obj["port-cost-mode"]; ok {
		_ = v
		if v != "" {
			m.PortCostMode = types.StringValue(v)
		} else {
			m.PortCostMode = types.StringNull()
		}
	} else {
		m.PortCostMode = types.StringNull()
	}
	if v, ok := obj["priority"]; ok {
		_ = v
		if n, err := client.ParseInt64(v); err == nil {
			m.Priority = types.Int64Value(n)
		} else {
			m.Priority = types.Int64Null()
		}
	} else {
		m.Priority = types.Int64Null()
	}
	if v, ok := obj["protocol-mode"]; ok {
		_ = v
		if v != "" {
			m.ProtocolMode = types.StringValue(v)
		} else {
			m.ProtocolMode = types.StringNull()
		}
	} else {
		m.ProtocolMode = types.StringNull()
	}
	if v, ok := obj["pvid"]; ok {
		_ = v
		if v != "" {
			m.Pvid = types.StringValue(v)
		} else {
			m.Pvid = types.StringNull()
		}
	} else {
		m.Pvid = types.StringNull()
	}
	if v, ok := obj["ra-guard"]; ok {
		_ = v
		if b, err := client.ParseBool(v); err == nil {
			m.RaGuard = types.BoolValue(b)
		} else {
			m.RaGuard = types.BoolNull()
		}
	} else {
		m.RaGuard = types.BoolNull()
	}
	if v, ok := obj["region-name"]; ok {
		_ = v
		if v != "" {
			m.RegionName = types.StringValue(v)
		} else {
			m.RegionName = types.StringNull()
		}
	} else {
		m.RegionName = types.StringNull()
	}
	if v, ok := obj["region-revision"]; ok {
		_ = v
		if v != "" {
			m.RegionRevision = types.StringValue(v)
		} else {
			m.RegionRevision = types.StringNull()
		}
	} else {
		m.RegionRevision = types.StringNull()
	}
	if v, ok := obj["transmit-hold-count"]; ok {
		_ = v
		if n, err := client.ParseInt64(v); err == nil {
			m.TransmitHoldCount = types.Int64Value(n)
		} else {
			m.TransmitHoldCount = types.Int64Null()
		}
	} else {
		m.TransmitHoldCount = types.Int64Null()
	}
	if v, ok := obj["vlan-filtering"]; ok {
		_ = v
		if b, err := client.ParseBool(v); err == nil {
			m.VLANFiltering = types.BoolValue(b)
		} else {
			m.VLANFiltering = types.BoolNull()
		}
	} else {
		m.VLANFiltering = types.BoolNull()
	}
}
