// Code generated by gen-provider. DO NOT EDIT.
package provider

import (
	"context"
	"fmt"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/ebogdum/terraform-provider-routeros/internal/client"
)

var (
	_ resource.Resource                = &RoutingBGPConnectionResource{}
	_ resource.ResourceWithImportState = &RoutingBGPConnectionResource{}
	_                                  = attr.Value(nil)
	_                                  = strings.TrimSpace
	_                                  = path.Root
)

type RoutingBGPConnectionResource struct {
	reg *client.Registry
}

type RoutingBGPConnectionModel struct {
	ID            types.String `tfsdk:"id"`
	Afi           types.String `tfsdk:"afi"`
	As            types.String `tfsdk:"as"`
	Comment       types.String `tfsdk:"comment"`
	Connect       types.String `tfsdk:"connect"`
	Disabled      types.Bool   `tfsdk:"disabled"`
	HoldTime      types.String `tfsdk:"hold_time"`
	Instance      types.String `tfsdk:"instance"`
	KeepaliveTime types.String `tfsdk:"keepalive_time"`
	Listen        types.String `tfsdk:"listen"`
	Multihop      types.String `tfsdk:"multihop"`
	Name          types.String `tfsdk:"name"`
	NexthopChoice types.String `tfsdk:"nexthop_choice"`
	RoutingTable  types.String `tfsdk:"routing_table"`
	TCPMd5Key     types.String `tfsdk:"tcp_md5_key"`
	UseBfd        types.String `tfsdk:"use_bfd"`
	Vrf           types.String `tfsdk:"vrf"`
	Router        types.String `tfsdk:"router"`
}

func NewRoutingBGPConnectionResource() resource.Resource { return &RoutingBGPConnectionResource{} }

func (r *RoutingBGPConnectionResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_routing_bgp_connection"
}

func (r *RoutingBGPConnectionResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	reg, diags := configureRegistry(req.ProviderData)
	resp.Diagnostics.Append(diags...)
	if reg != nil {
		r.reg = reg
	}
	_ = fmt.Sprintf
}

func (r *RoutingBGPConnectionResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Auto-test requires a typed-reference precondition (e.g. an existing peer,\ninstance, bridge of the specific kind). The current acc-test generator's\ngeneric data.routeros_interface.all lookup can't satisfy these. Use this\nresource manually with explicit references to a precondition resource\nin your config.\n",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Computed:      true,
				Description:   "RouterOS internal .id.",
				PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},
			"afi": schema.StringAttribute{
				Optional:    true,
				Computed:    true,
				Description: "",
			},
			"as": schema.StringAttribute{
				Optional:    true,
				Computed:    true,
				Description: "",
			},
			"comment": schema.StringAttribute{
				Optional:    true,
				Computed:    true,
				Description: "Free-form comment.",
			},
			"connect": schema.StringAttribute{
				Optional:    true,
				Computed:    true,
				Description: "",
			},
			"disabled": schema.BoolAttribute{
				Optional:    true,
				Computed:    true,
				Description: "Whether the entry is disabled.",
			},
			"hold_time": schema.StringAttribute{
				Optional:    true,
				Computed:    true,
				Description: "",
			},
			"instance": schema.StringAttribute{
				Optional:    true,
				Computed:    true,
				Description: "",
			},
			"keepalive_time": schema.StringAttribute{
				Optional:    true,
				Computed:    true,
				Description: "",
			},
			"listen": schema.StringAttribute{
				Optional:    true,
				Computed:    true,
				Description: "",
			},
			"multihop": schema.StringAttribute{
				Optional:    true,
				Computed:    true,
				Description: "",
			},
			"name": schema.StringAttribute{
				Optional:    true,
				Computed:    true,
				Description: "",
			},
			"nexthop_choice": schema.StringAttribute{
				Optional:    true,
				Computed:    true,
				Description: "",
			},
			"routing_table": schema.StringAttribute{
				Optional:    true,
				Computed:    true,
				Description: "",
			},
			"tcp_md5_key": schema.StringAttribute{
				Optional:    true,
				Computed:    true,
				Sensitive:   true,
				Description: "",
			},
			"use_bfd": schema.StringAttribute{
				Optional:    true,
				Computed:    true,
				Description: "",
			},
			"vrf": schema.StringAttribute{
				Optional:    true,
				Computed:    true,
				Description: "",
			},
			"router": schema.StringAttribute{
				Optional:    true,
				Description: "Name of the router (key in provider's `routers` map). Omit to use the default.",
			},
		},
	}
}

func (r *RoutingBGPConnectionResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan RoutingBGPConnectionModel
	if diags := req.Plan.Get(ctx, &plan); diags.HasError() {
		resp.Diagnostics.Append(diags...)
		return
	}
	c := pickClient(r.reg, plan.Router, &resp.Diagnostics)
	if c == nil {
		return
	}
	body := client.Object{}
	if !(plan.Afi.IsNull() || plan.Afi.IsUnknown()) {
		body["afi"] = plan.Afi.ValueString()
	}
	if !(plan.As.IsNull() || plan.As.IsUnknown()) {
		body["as"] = plan.As.ValueString()
	}
	if !(plan.Comment.IsNull() || plan.Comment.IsUnknown()) {
		body["comment"] = plan.Comment.ValueString()
	}
	if !(plan.Connect.IsNull() || plan.Connect.IsUnknown()) {
		body["connect"] = plan.Connect.ValueString()
	}
	if !(plan.Disabled.IsNull() || plan.Disabled.IsUnknown()) {
		body["disabled"] = client.FormatBool(plan.Disabled.ValueBool())
	}
	if !(plan.HoldTime.IsNull() || plan.HoldTime.IsUnknown()) {
		body["hold-time"] = plan.HoldTime.ValueString()
	}
	if !(plan.Instance.IsNull() || plan.Instance.IsUnknown()) {
		body["instance"] = plan.Instance.ValueString()
	}
	if !(plan.KeepaliveTime.IsNull() || plan.KeepaliveTime.IsUnknown()) {
		body["keepalive-time"] = plan.KeepaliveTime.ValueString()
	}
	if !(plan.Listen.IsNull() || plan.Listen.IsUnknown()) {
		body["listen"] = plan.Listen.ValueString()
	}
	if !(plan.Multihop.IsNull() || plan.Multihop.IsUnknown()) {
		body["multihop"] = plan.Multihop.ValueString()
	}
	if !(plan.Name.IsNull() || plan.Name.IsUnknown()) {
		body["name"] = plan.Name.ValueString()
	}
	if !(plan.NexthopChoice.IsNull() || plan.NexthopChoice.IsUnknown()) {
		body["nexthop-choice"] = plan.NexthopChoice.ValueString()
	}
	if !(plan.RoutingTable.IsNull() || plan.RoutingTable.IsUnknown()) {
		body["routing-table"] = plan.RoutingTable.ValueString()
	}
	if !(plan.TCPMd5Key.IsNull() || plan.TCPMd5Key.IsUnknown()) {
		body["tcp-md5-key"] = plan.TCPMd5Key.ValueString()
	}
	if !(plan.UseBfd.IsNull() || plan.UseBfd.IsUnknown()) {
		body["use-bfd"] = plan.UseBfd.ValueString()
	}
	if !(plan.Vrf.IsNull() || plan.Vrf.IsUnknown()) {
		body["vrf"] = plan.Vrf.ValueString()
	}
	obj, err := c.Add(ctx, "/routing/bgp/connection", body)
	if err != nil {
		resp.Diagnostics.AddError("Create /routing/bgp/connection failed", err.Error())
		return
	}
	routingBGPConnectionApply(ctx, obj, &plan)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *RoutingBGPConnectionResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state RoutingBGPConnectionModel
	if diags := req.State.Get(ctx, &state); diags.HasError() {
		resp.Diagnostics.Append(diags...)
		return
	}
	c := pickClient(r.reg, state.Router, &resp.Diagnostics)
	if c == nil {
		return
	}
	obj, err := c.GetByID(ctx, "/routing/bgp/connection", state.ID.ValueString())
	if err != nil {
		if client.IsNotFound(err) {
			resp.State.RemoveResource(ctx)
			return
		}
		resp.Diagnostics.AddError("Read /routing/bgp/connection failed", err.Error())
		return
	}
	routingBGPConnectionApply(ctx, obj, &state)
	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *RoutingBGPConnectionResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan, state RoutingBGPConnectionModel
	if diags := req.Plan.Get(ctx, &plan); diags.HasError() {
		resp.Diagnostics.Append(diags...)
		return
	}
	if diags := req.State.Get(ctx, &state); diags.HasError() {
		resp.Diagnostics.Append(diags...)
		return
	}
	c := pickClient(r.reg, plan.Router, &resp.Diagnostics)
	if c == nil {
		return
	}
	body := client.Object{}
	if !plan.Afi.Equal(state.Afi) {
		body["afi"] = plan.Afi.ValueString()
	}
	if !plan.As.Equal(state.As) {
		body["as"] = plan.As.ValueString()
	}
	if !plan.Comment.Equal(state.Comment) {
		body["comment"] = plan.Comment.ValueString()
	}
	if !plan.Connect.Equal(state.Connect) {
		body["connect"] = plan.Connect.ValueString()
	}
	if !plan.Disabled.Equal(state.Disabled) {
		body["disabled"] = client.FormatBool(plan.Disabled.ValueBool())
	}
	if !plan.HoldTime.Equal(state.HoldTime) {
		body["hold-time"] = plan.HoldTime.ValueString()
	}
	if !plan.Instance.Equal(state.Instance) {
		body["instance"] = plan.Instance.ValueString()
	}
	if !plan.KeepaliveTime.Equal(state.KeepaliveTime) {
		body["keepalive-time"] = plan.KeepaliveTime.ValueString()
	}
	if !plan.Listen.Equal(state.Listen) {
		body["listen"] = plan.Listen.ValueString()
	}
	if !plan.Multihop.Equal(state.Multihop) {
		body["multihop"] = plan.Multihop.ValueString()
	}
	if !plan.Name.Equal(state.Name) {
		body["name"] = plan.Name.ValueString()
	}
	if !plan.NexthopChoice.Equal(state.NexthopChoice) {
		body["nexthop-choice"] = plan.NexthopChoice.ValueString()
	}
	if !plan.RoutingTable.Equal(state.RoutingTable) {
		body["routing-table"] = plan.RoutingTable.ValueString()
	}
	if !plan.TCPMd5Key.Equal(state.TCPMd5Key) {
		body["tcp-md5-key"] = plan.TCPMd5Key.ValueString()
	}
	if !plan.UseBfd.Equal(state.UseBfd) {
		body["use-bfd"] = plan.UseBfd.ValueString()
	}
	if !plan.Vrf.Equal(state.Vrf) {
		body["vrf"] = plan.Vrf.ValueString()
	}
	if len(body) > 0 {
		obj, err := c.Set(ctx, "/routing/bgp/connection", state.ID.ValueString(), body)
		if err != nil {
			resp.Diagnostics.AddError("Update /routing/bgp/connection failed", err.Error())
			return
		}
		routingBGPConnectionApply(ctx, obj, &plan)
	} else {
		plan.ID = state.ID
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *RoutingBGPConnectionResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state RoutingBGPConnectionModel
	if diags := req.State.Get(ctx, &state); diags.HasError() {
		resp.Diagnostics.Append(diags...)
		return
	}
	c := pickClient(r.reg, state.Router, &resp.Diagnostics)
	if c == nil {
		return
	}
	if err := c.Remove(ctx, "/routing/bgp/connection", state.ID.ValueString()); err != nil {
		resp.Diagnostics.AddError("Delete /routing/bgp/connection failed", err.Error())
	}
}

func (r *RoutingBGPConnectionResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	// Import formats accepted:
	//   *<id>                            -> bare RouterOS .id on the default router
	//   <router>/*<id>                   -> .id on the named router
	//   <router>/<naturalkey>            -> resolved via List + filter
	//   <naturalkey>                     -> resolved on the default router
	id := req.ID
	routerName := ""
	if i := strings.Index(id, "/"); i > 0 && !strings.HasPrefix(id, "*") {
		routerName, id = id[:i], id[i+1:]
	}
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("router"), types.StringValue(routerName))...)
	if strings.HasPrefix(id, "*") {
		resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("id"), types.StringValue(id))...)
		return
	}
	c := pickClient(r.reg, types.StringValue(routerName), &resp.Diagnostics)
	if c == nil {
		return
	}
	rows, err := routingBGPConnectionLookupByNaturalKey(ctx, c, id)
	if err != nil {
		resp.Diagnostics.AddError("Import lookup failed", err.Error())
		return
	}
	if len(rows) == 0 {
		resp.Diagnostics.AddError("Import not found", fmt.Sprintf("no /routing/bgp/connection matches %q", id))
		return
	}
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("id"), types.StringValue(rows[0][".id"]))...)
}

// routingBGPConnectionLookupByNaturalKey searches for a record whose natural
// keys match id. The strategy: try every key declared in the schema overlay's
// natural_keys list (or fall back to "name") with equality matching.
func routingBGPConnectionLookupByNaturalKey(ctx context.Context, c *client.Client, id string) ([]client.Object, error) {
	keys := []string{}
	if len(keys) == 0 {
		keys = []string{"name"}
	}
	for _, k := range keys {
		rows, err := c.List(ctx, "/routing/bgp/connection", client.WithFilter(k, id))
		if err != nil {
			return nil, err
		}
		if len(rows) > 0 {
			return rows, nil
		}
	}
	return nil, nil
}

func routingBGPConnectionApply(ctx context.Context, obj client.Object, m *RoutingBGPConnectionModel) {
	_ = ctx
	m.ID = types.StringValue(obj[".id"])
	if v, ok := obj["afi"]; ok {
		_ = v
		if v != "" {
			m.Afi = types.StringValue(v)
		} else {
			m.Afi = types.StringNull()
		}
	} else {
		m.Afi = types.StringNull()
	}
	if v, ok := obj["as"]; ok {
		_ = v
		if v != "" {
			m.As = types.StringValue(v)
		} else {
			m.As = types.StringNull()
		}
	} else {
		m.As = types.StringNull()
	}
	if v, ok := obj["comment"]; ok {
		_ = v
		if v != "" {
			m.Comment = types.StringValue(v)
		} else {
			m.Comment = types.StringNull()
		}
	} else {
		m.Comment = types.StringNull()
	}
	if v, ok := obj["connect"]; ok {
		_ = v
		if v != "" {
			m.Connect = types.StringValue(v)
		} else {
			m.Connect = types.StringNull()
		}
	} else {
		m.Connect = types.StringNull()
	}
	if v, ok := obj["disabled"]; ok {
		_ = v
		if b, err := client.ParseBool(v); err == nil {
			m.Disabled = types.BoolValue(b)
		} else {
			m.Disabled = types.BoolNull()
		}
	} else {
		m.Disabled = types.BoolNull()
	}
	if v, ok := obj["hold-time"]; ok {
		_ = v
		if v != "" {
			m.HoldTime = types.StringValue(v)
		} else {
			m.HoldTime = types.StringNull()
		}
	} else {
		m.HoldTime = types.StringNull()
	}
	if v, ok := obj["instance"]; ok {
		_ = v
		if v != "" {
			m.Instance = types.StringValue(v)
		} else {
			m.Instance = types.StringNull()
		}
	} else {
		m.Instance = types.StringNull()
	}
	if v, ok := obj["keepalive-time"]; ok {
		_ = v
		if v != "" {
			m.KeepaliveTime = types.StringValue(v)
		} else {
			m.KeepaliveTime = types.StringNull()
		}
	} else {
		m.KeepaliveTime = types.StringNull()
	}
	if v, ok := obj["listen"]; ok {
		_ = v
		if v != "" {
			m.Listen = types.StringValue(v)
		} else {
			m.Listen = types.StringNull()
		}
	} else {
		m.Listen = types.StringNull()
	}
	if v, ok := obj["multihop"]; ok {
		_ = v
		if v != "" {
			m.Multihop = types.StringValue(v)
		} else {
			m.Multihop = types.StringNull()
		}
	} else {
		m.Multihop = types.StringNull()
	}
	if v, ok := obj["name"]; ok {
		_ = v
		if v != "" {
			m.Name = types.StringValue(v)
		} else {
			m.Name = types.StringNull()
		}
	} else {
		m.Name = types.StringNull()
	}
	if v, ok := obj["nexthop-choice"]; ok {
		_ = v
		if v != "" {
			m.NexthopChoice = types.StringValue(v)
		} else {
			m.NexthopChoice = types.StringNull()
		}
	} else {
		m.NexthopChoice = types.StringNull()
	}
	if v, ok := obj["routing-table"]; ok {
		_ = v
		if v != "" {
			m.RoutingTable = types.StringValue(v)
		} else {
			m.RoutingTable = types.StringNull()
		}
	} else {
		m.RoutingTable = types.StringNull()
	}
	// Sensitive: RouterOS scrubs the value on read. If the server returned
	// a value, decode it. Otherwise the plan value (user input) is what's
	// in m.TCPMd5Key already -- but if the user left it unset, resolve
	// the unknown to null so the framework accepts the state.
	if v, ok := obj["tcp-md5-key"]; ok && v != "" {
		_ = v
		if v != "" {
			m.TCPMd5Key = types.StringValue(v)
		} else {
			m.TCPMd5Key = types.StringNull()
		}
	} else if m.TCPMd5Key.IsUnknown() {
		m.TCPMd5Key = types.StringNull()
	}
	if v, ok := obj["use-bfd"]; ok {
		_ = v
		if v != "" {
			m.UseBfd = types.StringValue(v)
		} else {
			m.UseBfd = types.StringNull()
		}
	} else {
		m.UseBfd = types.StringNull()
	}
	if v, ok := obj["vrf"]; ok {
		_ = v
		if v != "" {
			m.Vrf = types.StringValue(v)
		} else {
			m.Vrf = types.StringNull()
		}
	} else {
		m.Vrf = types.StringNull()
	}
}
