// Code generated by gen-provider. DO NOT EDIT.
package provider

import (
	"context"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/ebogdum/terraform-provider-routeros/internal/client"
	"github.com/ebogdum/terraform-provider-routeros/internal/schemautil"
)

var (
	_ resource.Resource                = &SystemWatchdogResource{}
	_ resource.ResourceWithImportState = &SystemWatchdogResource{}
	_                                  = path.Root
	_                                  = fmt.Sprintf
)

type SystemWatchdogResource struct {
	reg *client.Registry
}

type SystemWatchdogModel struct {
	ID                 types.String `tfsdk:"id"`
	AutoSendSupout     types.Bool   `tfsdk:"auto_send_supout"`
	AutomaticSupout    types.Bool   `tfsdk:"automatic_supout"`
	NoPingDelay        types.String `tfsdk:"no_ping_delay"`
	PingStartAfterBoot types.String `tfsdk:"ping_start_after_boot"`
	PingTimeout        types.String `tfsdk:"ping_timeout"`
	SendEmailFrom      types.String `tfsdk:"send_email_from"`
	SendEmailTo        types.String `tfsdk:"send_email_to"`
	SendSMTPServer     types.String `tfsdk:"send_smtp_server"`
	WatchAddress       types.String `tfsdk:"watch_address"`
	WatchdogTimer      types.Bool   `tfsdk:"watchdog_timer"`
	Router             types.String `tfsdk:"router"`
}

func NewSystemWatchdogResource() resource.Resource { return &SystemWatchdogResource{} }

func (r *SystemWatchdogResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_system_watchdog"
}

func (r *SystemWatchdogResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	reg, diags := configureRegistry(req.ProviderData)
	resp.Diagnostics.Append(diags...)
	if reg != nil {
		r.reg = reg
	}
}

func (r *SystemWatchdogResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Singleton; misconfig can soft-brick — skip in acc",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Computed:      true,
				Description:   "Stable identifier (the singleton's menu path, optionally namespaced by router).",
				PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},
			"auto_send_supout": schema.BoolAttribute{Optional: true, Computed: true,
				Description: "After the support output file is automatically generated, it can be sent by email.",
			},
			"automatic_supout": schema.BoolAttribute{Optional: true, Computed: true,
				Description: "When software failure happens, a file named \"autosupout.rif\" is generated automatically. The previous \"autosupout.rif\" file is renamed to \"autosupout.old.rif\".",
			},
			"no_ping_delay": schema.StringAttribute{Optional: true, Computed: true,
				Description: "Specifies how long will it wait before trying to reach the watch-address.",
			},
			"ping_start_after_boot": schema.StringAttribute{Optional: true, Computed: true,
				Description:   "",
				Validators:    []validator.String{schemautil.IsDurationRouterOS()},
				PlanModifiers: []planmodifier.String{schemautil.NormalizeDuration()},
			},
			"ping_timeout": schema.StringAttribute{Optional: true, Computed: true,
				Description:   "Specifies the time interval in which the device will be pinged 6 times (after \"no-ping-delay\").",
				Validators:    []validator.String{schemautil.IsDurationRouterOS()},
				PlanModifiers: []planmodifier.String{schemautil.NormalizeDuration()},
			},
			"send_email_from": schema.StringAttribute{Optional: true, Computed: true,
				Description: "The e-mail address to send the support output file from. If not set, the value set in /tool e-mail is used.",
			},
			"send_email_to": schema.StringAttribute{Optional: true, Computed: true,
				Description: "The e-mail address to send the support output file to.",
			},
			"send_smtp_server": schema.StringAttribute{Optional: true, Computed: true,
				Description: "SMTP server address to send the support output file through. If not set, the value set in /tool e-mail is used.",
			},
			"watch_address": schema.StringAttribute{Optional: true, Computed: true,
				Description: "The system will reboot, in case 6 sequential pings to the given IP address will fail. If set to none this feature is disabled. By default, the router will reboot every 6 minutes if the watch-address is set and not reachable.",
			},
			"watchdog_timer": schema.BoolAttribute{Optional: true, Computed: true,
				Description: "Whether to reboot if a system is unresponsive for a minute.",
			},
			"router": schema.StringAttribute{Optional: true,
				Description: "Name of the router (key in provider's `routers` map). Omit to use the default.",
			},
		},
	}
}

func (r *SystemWatchdogResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan SystemWatchdogModel
	if d := req.Plan.Get(ctx, &plan); d.HasError() {
		resp.Diagnostics.Append(d...)
		return
	}
	systemWatchdogUpsert(ctx, r.reg, &plan, &resp.Diagnostics)
	if resp.Diagnostics.HasError() {
		return
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *SystemWatchdogResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan SystemWatchdogModel
	if d := req.Plan.Get(ctx, &plan); d.HasError() {
		resp.Diagnostics.Append(d...)
		return
	}
	systemWatchdogUpsert(ctx, r.reg, &plan, &resp.Diagnostics)
	if resp.Diagnostics.HasError() {
		return
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *SystemWatchdogResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state SystemWatchdogModel
	if d := req.State.Get(ctx, &state); d.HasError() {
		resp.Diagnostics.Append(d...)
		return
	}
	c := pickClient(r.reg, state.Router, &resp.Diagnostics)
	if c == nil {
		return
	}
	obj, err := c.GetSingleton(ctx, "/system/watchdog")
	if err != nil {
		resp.Diagnostics.AddError("Read /system/watchdog failed", err.Error())
		return
	}
	systemWatchdogApply(ctx, obj, &state)
	state.ID = types.StringValue(stateIDFor("/system/watchdog", state.Router))
	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *SystemWatchdogResource) Delete(_ context.Context, _ resource.DeleteRequest, _ *resource.DeleteResponse) {
	// Singleton menus aren't removable; just drop the state.
}

func (r *SystemWatchdogResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	// Import format: "<router>" or empty for default.
	routerName := req.ID
	if routerName == "/system/watchdog" {
		routerName = ""
	}
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("router"), types.StringValue(routerName))...)
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("id"), types.StringValue(stateIDFor("/system/watchdog", types.StringValue(routerName))))...)
}

func systemWatchdogUpsert(ctx context.Context, reg *client.Registry, plan *SystemWatchdogModel, diags *diagBuf) {
	c := pickClient(reg, plan.Router, diags)
	if c == nil {
		return
	}
	body := client.Object{}
	if !(plan.AutoSendSupout.IsNull() || plan.AutoSendSupout.IsUnknown()) {
		body["auto-send-supout"] = client.FormatBool(plan.AutoSendSupout.ValueBool())
	}
	if !(plan.AutomaticSupout.IsNull() || plan.AutomaticSupout.IsUnknown()) {
		body["automatic-supout"] = client.FormatBool(plan.AutomaticSupout.ValueBool())
	}
	if !(plan.NoPingDelay.IsNull() || plan.NoPingDelay.IsUnknown()) {
		body["no-ping-delay"] = plan.NoPingDelay.ValueString()
	}
	if !(plan.PingStartAfterBoot.IsNull() || plan.PingStartAfterBoot.IsUnknown()) {
		body["ping-start-after-boot"] = plan.PingStartAfterBoot.ValueString()
	}
	if !(plan.PingTimeout.IsNull() || plan.PingTimeout.IsUnknown()) {
		body["ping-timeout"] = plan.PingTimeout.ValueString()
	}
	if !(plan.SendEmailFrom.IsNull() || plan.SendEmailFrom.IsUnknown()) {
		body["send-email-from"] = plan.SendEmailFrom.ValueString()
	}
	if !(plan.SendEmailTo.IsNull() || plan.SendEmailTo.IsUnknown()) {
		body["send-email-to"] = plan.SendEmailTo.ValueString()
	}
	if !(plan.SendSMTPServer.IsNull() || plan.SendSMTPServer.IsUnknown()) {
		body["send-smtp-server"] = plan.SendSMTPServer.ValueString()
	}
	if !(plan.WatchAddress.IsNull() || plan.WatchAddress.IsUnknown()) {
		body["watch-address"] = plan.WatchAddress.ValueString()
	}
	if !(plan.WatchdogTimer.IsNull() || plan.WatchdogTimer.IsUnknown()) {
		body["watchdog-timer"] = client.FormatBool(plan.WatchdogTimer.ValueBool())
	}
	obj, err := c.SetSingleton(ctx, "/system/watchdog", body)
	if err != nil {
		diags.AddError("Upsert /system/watchdog failed", err.Error())
		return
	}
	systemWatchdogApply(ctx, obj, plan)
	plan.ID = types.StringValue(stateIDFor("/system/watchdog", plan.Router))
}

func systemWatchdogApply(ctx context.Context, obj client.Object, m *SystemWatchdogModel) {
	_ = ctx
	if v, ok := obj["auto-send-supout"]; ok {
		_ = v
		if b, err := client.ParseBool(v); err == nil {
			m.AutoSendSupout = types.BoolValue(b)
		} else {
			m.AutoSendSupout = types.BoolNull()
		}
	}
	if v, ok := obj["automatic-supout"]; ok {
		_ = v
		if b, err := client.ParseBool(v); err == nil {
			m.AutomaticSupout = types.BoolValue(b)
		} else {
			m.AutomaticSupout = types.BoolNull()
		}
	}
	if v, ok := obj["no-ping-delay"]; ok {
		_ = v
		if v != "" {
			m.NoPingDelay = types.StringValue(v)
		} else {
			m.NoPingDelay = types.StringNull()
		}
	}
	if v, ok := obj["ping-start-after-boot"]; ok {
		_ = v
		if v != "" {
			m.PingStartAfterBoot = types.StringValue(v)
		} else {
			m.PingStartAfterBoot = types.StringNull()
		}
	}
	if v, ok := obj["ping-timeout"]; ok {
		_ = v
		if v != "" {
			m.PingTimeout = types.StringValue(v)
		} else {
			m.PingTimeout = types.StringNull()
		}
	}
	if v, ok := obj["send-email-from"]; ok {
		_ = v
		if v != "" {
			m.SendEmailFrom = types.StringValue(v)
		} else {
			m.SendEmailFrom = types.StringNull()
		}
	}
	if v, ok := obj["send-email-to"]; ok {
		_ = v
		if v != "" {
			m.SendEmailTo = types.StringValue(v)
		} else {
			m.SendEmailTo = types.StringNull()
		}
	}
	if v, ok := obj["send-smtp-server"]; ok {
		_ = v
		if v != "" {
			m.SendSMTPServer = types.StringValue(v)
		} else {
			m.SendSMTPServer = types.StringNull()
		}
	}
	if v, ok := obj["watch-address"]; ok {
		_ = v
		if v != "" {
			m.WatchAddress = types.StringValue(v)
		} else {
			m.WatchAddress = types.StringNull()
		}
	}
	if v, ok := obj["watchdog-timer"]; ok {
		_ = v
		if b, err := client.ParseBool(v); err == nil {
			m.WatchdogTimer = types.BoolValue(b)
		} else {
			m.WatchdogTimer = types.BoolNull()
		}
	}
}
