// Code generated by gen-provider. DO NOT EDIT.
package provider

import (
	"context"
	"fmt"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/ebogdum/terraform-provider-routeros/internal/client"
	"github.com/ebogdum/terraform-provider-routeros/internal/schemautil"
)

var (
	_ resource.Resource                = &InterfaceEthernetResource{}
	_ resource.ResourceWithImportState = &InterfaceEthernetResource{}
	_                                  = attr.Value(nil)
	_                                  = strings.TrimSpace
	_                                  = path.Root
)

type InterfaceEthernetResource struct {
	reg *client.Registry
}

type InterfaceEthernetModel struct {
	ID                      types.String `tfsdk:"id"`
	Advertise               types.List   `tfsdk:"advertise"`
	ARP                     types.String `tfsdk:"arp"`
	ARPTimeout              types.String `tfsdk:"arp_timeout"`
	AutoNegotiation         types.String `tfsdk:"auto_negotiation"`
	CableSettings           types.String `tfsdk:"cable_settings"`
	ComboMode               types.String `tfsdk:"combo_mode"`
	Comment                 types.String `tfsdk:"comment"`
	DefaultName             types.String `tfsdk:"default_name"`
	DisableRunningCheck     types.Bool   `tfsdk:"disable_running_check"`
	Disabled                types.Bool   `tfsdk:"disabled"`
	FecMode                 types.String `tfsdk:"fec_mode"`
	L2mtu                   types.String `tfsdk:"l2mtu"`
	LoopProtect             types.String `tfsdk:"loop_protect"`
	LoopProtectDisableTime  types.String `tfsdk:"loop_protect_disable_time"`
	LoopProtectSendInterval types.String `tfsdk:"loop_protect_send_interval"`
	LoopProtectStatus       types.String `tfsdk:"loop_protect_status"`
	MACAddress              types.String `tfsdk:"mac_address"`
	MTU                     types.Int64  `tfsdk:"mtu"`
	Name                    types.String `tfsdk:"name"`
	OrigMACAddress          types.String `tfsdk:"orig_mac_address"`
	Running                 types.Bool   `tfsdk:"running"`
	RxBroadcast             types.Int64  `tfsdk:"rx_broadcast"`
	RxBytes                 types.Int64  `tfsdk:"rx_bytes"`
	RxFlowControl           types.String `tfsdk:"rx_flow_control"`
	RxMulticast             types.Int64  `tfsdk:"rx_multicast"`
	RxPacket                types.Int64  `tfsdk:"rx_packet"`
	SfpShutdownTemperature  types.Int64  `tfsdk:"sfp_shutdown_temperature"`
	Speed                   types.String `tfsdk:"speed"`
	TxBroadcast             types.Int64  `tfsdk:"tx_broadcast"`
	TxBytes                 types.Int64  `tfsdk:"tx_bytes"`
	TxFlowControl           types.String `tfsdk:"tx_flow_control"`
	TxMulticast             types.Int64  `tfsdk:"tx_multicast"`
	TxPacket                types.Int64  `tfsdk:"tx_packet"`
	Router                  types.String `tfsdk:"router"`
}

func NewInterfaceEthernetResource() resource.Resource { return &InterfaceEthernetResource{} }

func (r *InterfaceEthernetResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_interface_ethernet"
}

func (r *InterfaceEthernetResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	reg, diags := configureRegistry(req.ProviderData)
	resp.Diagnostics.Append(diags...)
	if reg != nil {
		r.reg = reg
	}
	_ = fmt.Sprintf
}

func (r *InterfaceEthernetResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "/interface/ethernet entries are auto-created from the physical NICs; can't be added via TF.",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Computed:      true,
				Description:   "RouterOS internal .id.",
				PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},
			"advertise": schema.ListAttribute{
				Optional:    true,
				Computed:    true,
				ElementType: types.StringType,
				Description: "",
			},
			"arp": schema.StringAttribute{
				Optional:    true,
				Computed:    true,
				Description: "",
				Validators:  []validator.String{schemautil.OneOf([]string{"disabled", "enabled", "proxy-arp", "reply-only", "local-proxy-arp"}...)},
			},
			"arp_timeout": schema.StringAttribute{
				Optional:      true,
				Computed:      true,
				Description:   "",
				Validators:    []validator.String{schemautil.IsDurationRouterOS()},
				PlanModifiers: []planmodifier.String{schemautil.NormalizeDuration()},
			},
			"auto_negotiation": schema.StringAttribute{
				Optional:    true,
				Computed:    true,
				Description: "",
				Validators:  []validator.String{schemautil.OneOf([]string{"incomplete", "done", "no negotiation", "failed", "restarted", "disabled", "not available"}...)},
			},
			"cable_settings": schema.StringAttribute{
				Optional:    true,
				Computed:    true,
				Description: "",
			},
			"combo_mode": schema.StringAttribute{
				Optional:    true,
				Computed:    true,
				Description: "",
				Validators:  []validator.String{schemautil.OneOf([]string{"auto", "copper", "sfp"}...)},
			},
			"comment": schema.StringAttribute{
				Optional:    true,
				Computed:    true,
				Description: "Free-form comment.",
			},
			"default_name": schema.StringAttribute{
				Optional:    true,
				Computed:    true,
				Description: "",
			},
			"disable_running_check": schema.BoolAttribute{
				Optional:    true,
				Computed:    true,
				Description: "",
			},
			"disabled": schema.BoolAttribute{
				Optional:    true,
				Computed:    true,
				Description: "",
			},
			"fec_mode": schema.StringAttribute{
				Optional:    true,
				Computed:    true,
				Description: "",
				Validators:  []validator.String{schemautil.OneOf([]string{"off", "auto", "fec74", "fec91"}...)},
			},
			"l2mtu": schema.StringAttribute{
				Optional:    true,
				Computed:    true,
				Description: "",
			},
			"loop_protect": schema.StringAttribute{
				Optional:    true,
				Computed:    true,
				Description: "",
				Validators:  []validator.String{schemautil.OneOf([]string{"default", "off", "on"}...)},
			},
			"loop_protect_disable_time": schema.StringAttribute{
				Optional:      true,
				Computed:      true,
				Description:   "",
				Validators:    []validator.String{schemautil.IsDurationRouterOS()},
				PlanModifiers: []planmodifier.String{schemautil.NormalizeDuration()},
			},
			"loop_protect_send_interval": schema.StringAttribute{
				Optional:      true,
				Computed:      true,
				Description:   "",
				Validators:    []validator.String{schemautil.IsDurationRouterOS()},
				PlanModifiers: []planmodifier.String{schemautil.NormalizeDuration()},
			},
			"loop_protect_status": schema.StringAttribute{
				Optional:    true,
				Computed:    true,
				Description: "",
			},
			"mac_address": schema.StringAttribute{
				Optional:      true,
				Computed:      true,
				Description:   "MAC address to be mapped to",
				Validators:    []validator.String{schemautil.IsMAC()},
				PlanModifiers: []planmodifier.String{schemautil.NormalizeMAC()},
			},
			"mtu": schema.Int64Attribute{
				Optional:    true,
				Computed:    true,
				Description: "",
			},
			"name": schema.StringAttribute{
				Optional:    true,
				Computed:    true,
				Description: "",
			},
			"orig_mac_address": schema.StringAttribute{
				Optional:      true,
				Computed:      true,
				Description:   "",
				Validators:    []validator.String{schemautil.IsMAC()},
				PlanModifiers: []planmodifier.String{schemautil.NormalizeMAC()},
			},
			"running": schema.BoolAttribute{
				Optional:    true,
				Computed:    true,
				Description: "",
			},
			"rx_broadcast": schema.Int64Attribute{
				Optional:    true,
				Computed:    true,
				Description: "",
			},
			"rx_bytes": schema.Int64Attribute{
				Optional:    true,
				Computed:    true,
				Description: "",
			},
			"rx_flow_control": schema.StringAttribute{
				Optional:    true,
				Computed:    true,
				Description: "",
				Validators:  []validator.String{schemautil.OneOf([]string{"off", "on", "auto"}...)},
			},
			"rx_multicast": schema.Int64Attribute{
				Optional:    true,
				Computed:    true,
				Description: "",
			},
			"rx_packet": schema.Int64Attribute{
				Optional:    true,
				Computed:    true,
				Description: "",
			},
			"sfp_shutdown_temperature": schema.Int64Attribute{
				Optional:    true,
				Computed:    true,
				Description: "",
			},
			"speed": schema.StringAttribute{
				Optional:    true,
				Computed:    true,
				Description: "",
				Validators:  []validator.String{schemautil.OneOf([]string{"10M baseT half", "10M baseT full", "100M baseT half", "100M baseT full", "1G baseT half", "1G baseT full", "10G baseT", "2.5G baseX", "40G baseCR4", "40G baseSR4 LR4", "25G baseCR", "25G baseSR LR", "50G baseCR2", "100G baseSR4 LR4", "100G baseCR4", "50G baseSR2 LR2", "1G baseX", "10G baseCR", "10G baseSR LR", "2.5G baseT", "5G baseT", "50G baseSR LR", "50G baseCR", "100G baseSR2 LR2", "100G baseCR2", "200G baseSR4 LR4", "200G baseCR4", "400G baseSR8 LR8", "400G baseCR8", "100M baseFX half", "100M baseFX full"}...)},
			},
			"tx_broadcast": schema.Int64Attribute{
				Optional:    true,
				Computed:    true,
				Description: "",
			},
			"tx_bytes": schema.Int64Attribute{
				Optional:    true,
				Computed:    true,
				Description: "",
			},
			"tx_flow_control": schema.StringAttribute{
				Optional:    true,
				Computed:    true,
				Description: "",
				Validators:  []validator.String{schemautil.OneOf([]string{"off", "on", "auto"}...)},
			},
			"tx_multicast": schema.Int64Attribute{
				Optional:    true,
				Computed:    true,
				Description: "",
			},
			"tx_packet": schema.Int64Attribute{
				Optional:    true,
				Computed:    true,
				Description: "",
			},
			"router": schema.StringAttribute{
				Optional:    true,
				Description: "Name of the router (key in provider's `routers` map). Omit to use the default.",
			},
		},
	}
}

func (r *InterfaceEthernetResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan InterfaceEthernetModel
	if diags := req.Plan.Get(ctx, &plan); diags.HasError() {
		resp.Diagnostics.Append(diags...)
		return
	}
	c := pickClient(r.reg, plan.Router, &resp.Diagnostics)
	if c == nil {
		return
	}
	body := client.Object{}
	if !(plan.Advertise.IsNull() || plan.Advertise.IsUnknown()) {
		body["advertise"] = encodeStringList(ctx, plan.Advertise)
	}
	if !(plan.ARP.IsNull() || plan.ARP.IsUnknown()) {
		body["arp"] = plan.ARP.ValueString()
	}
	if !(plan.ARPTimeout.IsNull() || plan.ARPTimeout.IsUnknown()) {
		body["arp-timeout"] = plan.ARPTimeout.ValueString()
	}
	if !(plan.CableSettings.IsNull() || plan.CableSettings.IsUnknown()) {
		body["cable-settings"] = plan.CableSettings.ValueString()
	}
	if !(plan.ComboMode.IsNull() || plan.ComboMode.IsUnknown()) {
		body["combo-mode"] = plan.ComboMode.ValueString()
	}
	if !(plan.Comment.IsNull() || plan.Comment.IsUnknown()) {
		body["comment"] = plan.Comment.ValueString()
	}
	if !(plan.DisableRunningCheck.IsNull() || plan.DisableRunningCheck.IsUnknown()) {
		body["disable-running-check"] = client.FormatBool(plan.DisableRunningCheck.ValueBool())
	}
	if !(plan.Disabled.IsNull() || plan.Disabled.IsUnknown()) {
		body["disabled"] = client.FormatBool(plan.Disabled.ValueBool())
	}
	if !(plan.FecMode.IsNull() || plan.FecMode.IsUnknown()) {
		body["fec-mode"] = plan.FecMode.ValueString()
	}
	if !(plan.L2mtu.IsNull() || plan.L2mtu.IsUnknown()) {
		body["l2mtu"] = plan.L2mtu.ValueString()
	}
	if !(plan.LoopProtect.IsNull() || plan.LoopProtect.IsUnknown()) {
		body["loop-protect"] = plan.LoopProtect.ValueString()
	}
	if !(plan.LoopProtectDisableTime.IsNull() || plan.LoopProtectDisableTime.IsUnknown()) {
		body["loop-protect-disable-time"] = plan.LoopProtectDisableTime.ValueString()
	}
	if !(plan.LoopProtectSendInterval.IsNull() || plan.LoopProtectSendInterval.IsUnknown()) {
		body["loop-protect-send-interval"] = plan.LoopProtectSendInterval.ValueString()
	}
	if !(plan.MACAddress.IsNull() || plan.MACAddress.IsUnknown()) {
		body["mac-address"] = plan.MACAddress.ValueString()
	}
	if !(plan.MTU.IsNull() || plan.MTU.IsUnknown()) {
		body["mtu"] = client.FormatInt64(plan.MTU.ValueInt64())
	}
	if !(plan.Name.IsNull() || plan.Name.IsUnknown()) {
		body["name"] = plan.Name.ValueString()
	}
	if !(plan.OrigMACAddress.IsNull() || plan.OrigMACAddress.IsUnknown()) {
		body["orig-mac-address"] = plan.OrigMACAddress.ValueString()
	}
	if !(plan.RxFlowControl.IsNull() || plan.RxFlowControl.IsUnknown()) {
		body["rx-flow-control"] = plan.RxFlowControl.ValueString()
	}
	if !(plan.SfpShutdownTemperature.IsNull() || plan.SfpShutdownTemperature.IsUnknown()) {
		body["sfp-shutdown-temperature"] = client.FormatInt64(plan.SfpShutdownTemperature.ValueInt64())
	}
	if !(plan.Speed.IsNull() || plan.Speed.IsUnknown()) {
		body["speed"] = plan.Speed.ValueString()
	}
	if !(plan.TxFlowControl.IsNull() || plan.TxFlowControl.IsUnknown()) {
		body["tx-flow-control"] = plan.TxFlowControl.ValueString()
	}
	obj, err := c.Add(ctx, "/interface/ethernet", body)
	if err != nil {
		resp.Diagnostics.AddError("Create /interface/ethernet failed", err.Error())
		return
	}
	interfaceEthernetApply(ctx, obj, &plan)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *InterfaceEthernetResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state InterfaceEthernetModel
	if diags := req.State.Get(ctx, &state); diags.HasError() {
		resp.Diagnostics.Append(diags...)
		return
	}
	c := pickClient(r.reg, state.Router, &resp.Diagnostics)
	if c == nil {
		return
	}
	obj, err := c.GetByID(ctx, "/interface/ethernet", state.ID.ValueString())
	if err != nil {
		if client.IsNotFound(err) {
			resp.State.RemoveResource(ctx)
			return
		}
		resp.Diagnostics.AddError("Read /interface/ethernet failed", err.Error())
		return
	}
	interfaceEthernetApply(ctx, obj, &state)
	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *InterfaceEthernetResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan, state InterfaceEthernetModel
	if diags := req.Plan.Get(ctx, &plan); diags.HasError() {
		resp.Diagnostics.Append(diags...)
		return
	}
	if diags := req.State.Get(ctx, &state); diags.HasError() {
		resp.Diagnostics.Append(diags...)
		return
	}
	c := pickClient(r.reg, plan.Router, &resp.Diagnostics)
	if c == nil {
		return
	}
	body := client.Object{}
	if !plan.Advertise.Equal(state.Advertise) {
		body["advertise"] = encodeStringList(ctx, plan.Advertise)
	}
	if !plan.ARP.Equal(state.ARP) {
		body["arp"] = plan.ARP.ValueString()
	}
	if !plan.ARPTimeout.Equal(state.ARPTimeout) {
		body["arp-timeout"] = plan.ARPTimeout.ValueString()
	}
	if !plan.CableSettings.Equal(state.CableSettings) {
		body["cable-settings"] = plan.CableSettings.ValueString()
	}
	if !plan.ComboMode.Equal(state.ComboMode) {
		body["combo-mode"] = plan.ComboMode.ValueString()
	}
	if !plan.Comment.Equal(state.Comment) {
		body["comment"] = plan.Comment.ValueString()
	}
	if !plan.DisableRunningCheck.Equal(state.DisableRunningCheck) {
		body["disable-running-check"] = client.FormatBool(plan.DisableRunningCheck.ValueBool())
	}
	if !plan.Disabled.Equal(state.Disabled) {
		body["disabled"] = client.FormatBool(plan.Disabled.ValueBool())
	}
	if !plan.FecMode.Equal(state.FecMode) {
		body["fec-mode"] = plan.FecMode.ValueString()
	}
	if !plan.L2mtu.Equal(state.L2mtu) {
		body["l2mtu"] = plan.L2mtu.ValueString()
	}
	if !plan.LoopProtect.Equal(state.LoopProtect) {
		body["loop-protect"] = plan.LoopProtect.ValueString()
	}
	if !plan.LoopProtectDisableTime.Equal(state.LoopProtectDisableTime) {
		body["loop-protect-disable-time"] = plan.LoopProtectDisableTime.ValueString()
	}
	if !plan.LoopProtectSendInterval.Equal(state.LoopProtectSendInterval) {
		body["loop-protect-send-interval"] = plan.LoopProtectSendInterval.ValueString()
	}
	if !plan.MACAddress.Equal(state.MACAddress) {
		body["mac-address"] = plan.MACAddress.ValueString()
	}
	if !plan.MTU.Equal(state.MTU) {
		body["mtu"] = client.FormatInt64(plan.MTU.ValueInt64())
	}
	if !plan.Name.Equal(state.Name) {
		body["name"] = plan.Name.ValueString()
	}
	if !plan.OrigMACAddress.Equal(state.OrigMACAddress) {
		body["orig-mac-address"] = plan.OrigMACAddress.ValueString()
	}
	if !plan.RxFlowControl.Equal(state.RxFlowControl) {
		body["rx-flow-control"] = plan.RxFlowControl.ValueString()
	}
	if !plan.SfpShutdownTemperature.Equal(state.SfpShutdownTemperature) {
		body["sfp-shutdown-temperature"] = client.FormatInt64(plan.SfpShutdownTemperature.ValueInt64())
	}
	if !plan.Speed.Equal(state.Speed) {
		body["speed"] = plan.Speed.ValueString()
	}
	if !plan.TxFlowControl.Equal(state.TxFlowControl) {
		body["tx-flow-control"] = plan.TxFlowControl.ValueString()
	}
	if len(body) > 0 {
		obj, err := c.Set(ctx, "/interface/ethernet", state.ID.ValueString(), body)
		if err != nil {
			resp.Diagnostics.AddError("Update /interface/ethernet failed", err.Error())
			return
		}
		interfaceEthernetApply(ctx, obj, &plan)
	} else {
		plan.ID = state.ID
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *InterfaceEthernetResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state InterfaceEthernetModel
	if diags := req.State.Get(ctx, &state); diags.HasError() {
		resp.Diagnostics.Append(diags...)
		return
	}
	c := pickClient(r.reg, state.Router, &resp.Diagnostics)
	if c == nil {
		return
	}
	if err := c.Remove(ctx, "/interface/ethernet", state.ID.ValueString()); err != nil {
		resp.Diagnostics.AddError("Delete /interface/ethernet failed", err.Error())
	}
}

func (r *InterfaceEthernetResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	// Import formats accepted:
	//   *<id>                            -> bare RouterOS .id on the default router
	//   <router>/*<id>                   -> .id on the named router
	//   <router>/<naturalkey>            -> resolved via List + filter
	//   <naturalkey>                     -> resolved on the default router
	id := req.ID
	routerName := ""
	if i := strings.Index(id, "/"); i > 0 && !strings.HasPrefix(id, "*") {
		routerName, id = id[:i], id[i+1:]
	}
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("router"), types.StringValue(routerName))...)
	if strings.HasPrefix(id, "*") {
		resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("id"), types.StringValue(id))...)
		return
	}
	c := pickClient(r.reg, types.StringValue(routerName), &resp.Diagnostics)
	if c == nil {
		return
	}
	rows, err := interfaceEthernetLookupByNaturalKey(ctx, c, id)
	if err != nil {
		resp.Diagnostics.AddError("Import lookup failed", err.Error())
		return
	}
	if len(rows) == 0 {
		resp.Diagnostics.AddError("Import not found", fmt.Sprintf("no /interface/ethernet matches %q", id))
		return
	}
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("id"), types.StringValue(rows[0][".id"]))...)
}

// interfaceEthernetLookupByNaturalKey searches for a record whose natural
// keys match id. The strategy: try every key declared in the schema overlay's
// natural_keys list (or fall back to "name") with equality matching.
func interfaceEthernetLookupByNaturalKey(ctx context.Context, c *client.Client, id string) ([]client.Object, error) {
	keys := []string{}
	if len(keys) == 0 {
		keys = []string{"name"}
	}
	for _, k := range keys {
		rows, err := c.List(ctx, "/interface/ethernet", client.WithFilter(k, id))
		if err != nil {
			return nil, err
		}
		if len(rows) > 0 {
			return rows, nil
		}
	}
	return nil, nil
}

func interfaceEthernetApply(ctx context.Context, obj client.Object, m *InterfaceEthernetModel) {
	_ = ctx
	m.ID = types.StringValue(obj[".id"])
	if v, ok := obj["advertise"]; ok {
		_ = v
		m.Advertise = decodeStringList(ctx, v)
	} else {
		m.Advertise = types.ListNull(types.StringType)
	}
	if v, ok := obj["arp"]; ok {
		_ = v
		if v != "" {
			m.ARP = types.StringValue(v)
		} else {
			m.ARP = types.StringNull()
		}
	} else {
		m.ARP = types.StringNull()
	}
	if v, ok := obj["arp-timeout"]; ok {
		_ = v
		if v != "" {
			m.ARPTimeout = types.StringValue(v)
		} else {
			m.ARPTimeout = types.StringNull()
		}
	} else {
		m.ARPTimeout = types.StringNull()
	}
	if v, ok := obj["auto-negotiation"]; ok {
		_ = v
		if v != "" {
			m.AutoNegotiation = types.StringValue(v)
		} else {
			m.AutoNegotiation = types.StringNull()
		}
	} else {
		m.AutoNegotiation = types.StringNull()
	}
	if v, ok := obj["cable-settings"]; ok {
		_ = v
		if v != "" {
			m.CableSettings = types.StringValue(v)
		} else {
			m.CableSettings = types.StringNull()
		}
	} else {
		m.CableSettings = types.StringNull()
	}
	if v, ok := obj["combo-mode"]; ok {
		_ = v
		if v != "" {
			m.ComboMode = types.StringValue(v)
		} else {
			m.ComboMode = types.StringNull()
		}
	} else {
		m.ComboMode = types.StringNull()
	}
	if v, ok := obj["comment"]; ok {
		_ = v
		if v != "" {
			m.Comment = types.StringValue(v)
		} else {
			m.Comment = types.StringNull()
		}
	} else {
		m.Comment = types.StringNull()
	}
	if v, ok := obj["default-name"]; ok {
		_ = v
		if v != "" {
			m.DefaultName = types.StringValue(v)
		} else {
			m.DefaultName = types.StringNull()
		}
	} else {
		m.DefaultName = types.StringNull()
	}
	if v, ok := obj["disable-running-check"]; ok {
		_ = v
		if b, err := client.ParseBool(v); err == nil {
			m.DisableRunningCheck = types.BoolValue(b)
		} else {
			m.DisableRunningCheck = types.BoolNull()
		}
	} else {
		m.DisableRunningCheck = types.BoolNull()
	}
	if v, ok := obj["disabled"]; ok {
		_ = v
		if b, err := client.ParseBool(v); err == nil {
			m.Disabled = types.BoolValue(b)
		} else {
			m.Disabled = types.BoolNull()
		}
	} else {
		m.Disabled = types.BoolNull()
	}
	if v, ok := obj["fec-mode"]; ok {
		_ = v
		if v != "" {
			m.FecMode = types.StringValue(v)
		} else {
			m.FecMode = types.StringNull()
		}
	} else {
		m.FecMode = types.StringNull()
	}
	if v, ok := obj["l2mtu"]; ok {
		_ = v
		if v != "" {
			m.L2mtu = types.StringValue(v)
		} else {
			m.L2mtu = types.StringNull()
		}
	} else {
		m.L2mtu = types.StringNull()
	}
	if v, ok := obj["loop-protect"]; ok {
		_ = v
		if v != "" {
			m.LoopProtect = types.StringValue(v)
		} else {
			m.LoopProtect = types.StringNull()
		}
	} else {
		m.LoopProtect = types.StringNull()
	}
	if v, ok := obj["loop-protect-disable-time"]; ok {
		_ = v
		if v != "" {
			m.LoopProtectDisableTime = types.StringValue(v)
		} else {
			m.LoopProtectDisableTime = types.StringNull()
		}
	} else {
		m.LoopProtectDisableTime = types.StringNull()
	}
	if v, ok := obj["loop-protect-send-interval"]; ok {
		_ = v
		if v != "" {
			m.LoopProtectSendInterval = types.StringValue(v)
		} else {
			m.LoopProtectSendInterval = types.StringNull()
		}
	} else {
		m.LoopProtectSendInterval = types.StringNull()
	}
	if v, ok := obj["loop-protect-status"]; ok {
		_ = v
		if v != "" {
			m.LoopProtectStatus = types.StringValue(v)
		} else {
			m.LoopProtectStatus = types.StringNull()
		}
	} else {
		m.LoopProtectStatus = types.StringNull()
	}
	if v, ok := obj["mac-address"]; ok {
		_ = v
		if v != "" {
			m.MACAddress = types.StringValue(v)
		} else {
			m.MACAddress = types.StringNull()
		}
	} else {
		m.MACAddress = types.StringNull()
	}
	if v, ok := obj["mtu"]; ok {
		_ = v
		if n, err := client.ParseInt64(v); err == nil {
			m.MTU = types.Int64Value(n)
		} else {
			m.MTU = types.Int64Null()
		}
	} else {
		m.MTU = types.Int64Null()
	}
	if v, ok := obj["name"]; ok {
		_ = v
		if v != "" {
			m.Name = types.StringValue(v)
		} else {
			m.Name = types.StringNull()
		}
	} else {
		m.Name = types.StringNull()
	}
	if v, ok := obj["orig-mac-address"]; ok {
		_ = v
		if v != "" {
			m.OrigMACAddress = types.StringValue(v)
		} else {
			m.OrigMACAddress = types.StringNull()
		}
	} else {
		m.OrigMACAddress = types.StringNull()
	}
	if v, ok := obj["running"]; ok {
		_ = v
		if b, err := client.ParseBool(v); err == nil {
			m.Running = types.BoolValue(b)
		} else {
			m.Running = types.BoolNull()
		}
	} else {
		m.Running = types.BoolNull()
	}
	if v, ok := obj["rx-broadcast"]; ok {
		_ = v
		if n, err := client.ParseInt64(v); err == nil {
			m.RxBroadcast = types.Int64Value(n)
		} else {
			m.RxBroadcast = types.Int64Null()
		}
	} else {
		m.RxBroadcast = types.Int64Null()
	}
	if v, ok := obj["rx-bytes"]; ok {
		_ = v
		if n, err := client.ParseInt64(v); err == nil {
			m.RxBytes = types.Int64Value(n)
		} else {
			m.RxBytes = types.Int64Null()
		}
	} else {
		m.RxBytes = types.Int64Null()
	}
	if v, ok := obj["rx-flow-control"]; ok {
		_ = v
		if v != "" {
			m.RxFlowControl = types.StringValue(v)
		} else {
			m.RxFlowControl = types.StringNull()
		}
	} else {
		m.RxFlowControl = types.StringNull()
	}
	if v, ok := obj["rx-multicast"]; ok {
		_ = v
		if n, err := client.ParseInt64(v); err == nil {
			m.RxMulticast = types.Int64Value(n)
		} else {
			m.RxMulticast = types.Int64Null()
		}
	} else {
		m.RxMulticast = types.Int64Null()
	}
	if v, ok := obj["rx-packet"]; ok {
		_ = v
		if n, err := client.ParseInt64(v); err == nil {
			m.RxPacket = types.Int64Value(n)
		} else {
			m.RxPacket = types.Int64Null()
		}
	} else {
		m.RxPacket = types.Int64Null()
	}
	if v, ok := obj["sfp-shutdown-temperature"]; ok {
		_ = v
		if n, err := client.ParseInt64(v); err == nil {
			m.SfpShutdownTemperature = types.Int64Value(n)
		} else {
			m.SfpShutdownTemperature = types.Int64Null()
		}
	} else {
		m.SfpShutdownTemperature = types.Int64Null()
	}
	if v, ok := obj["speed"]; ok {
		_ = v
		if v != "" {
			m.Speed = types.StringValue(v)
		} else {
			m.Speed = types.StringNull()
		}
	} else {
		m.Speed = types.StringNull()
	}
	if v, ok := obj["tx-broadcast"]; ok {
		_ = v
		if n, err := client.ParseInt64(v); err == nil {
			m.TxBroadcast = types.Int64Value(n)
		} else {
			m.TxBroadcast = types.Int64Null()
		}
	} else {
		m.TxBroadcast = types.Int64Null()
	}
	if v, ok := obj["tx-bytes"]; ok {
		_ = v
		if n, err := client.ParseInt64(v); err == nil {
			m.TxBytes = types.Int64Value(n)
		} else {
			m.TxBytes = types.Int64Null()
		}
	} else {
		m.TxBytes = types.Int64Null()
	}
	if v, ok := obj["tx-flow-control"]; ok {
		_ = v
		if v != "" {
			m.TxFlowControl = types.StringValue(v)
		} else {
			m.TxFlowControl = types.StringNull()
		}
	} else {
		m.TxFlowControl = types.StringNull()
	}
	if v, ok := obj["tx-multicast"]; ok {
		_ = v
		if n, err := client.ParseInt64(v); err == nil {
			m.TxMulticast = types.Int64Value(n)
		} else {
			m.TxMulticast = types.Int64Null()
		}
	} else {
		m.TxMulticast = types.Int64Null()
	}
	if v, ok := obj["tx-packet"]; ok {
		_ = v
		if n, err := client.ParseInt64(v); err == nil {
			m.TxPacket = types.Int64Value(n)
		} else {
			m.TxPacket = types.Int64Null()
		}
	} else {
		m.TxPacket = types.Int64Null()
	}
}
