// Code generated by gen-provider. DO NOT EDIT.
package provider

import (
	"context"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/ebogdum/terraform-provider-routeros/internal/client"
	"github.com/ebogdum/terraform-provider-routeros/internal/schemautil"
)

var (
	_ resource.Resource                = &SNMPResource{}
	_ resource.ResourceWithImportState = &SNMPResource{}
	_                                  = path.Root
	_                                  = fmt.Sprintf
)

type SNMPResource struct {
	reg *client.Registry
}

type SNMPModel struct {
	ID             types.String `tfsdk:"id"`
	Contact        types.String `tfsdk:"contact"`
	Enabled        types.Bool   `tfsdk:"enabled"`
	EngineID       types.String `tfsdk:"engine_id"`
	EngineIDSuffix types.String `tfsdk:"engine_id_suffix"`
	Location       types.String `tfsdk:"location"`
	SrcAddress     types.String `tfsdk:"src_address"`
	TrapCommunity  types.String `tfsdk:"trap_community"`
	TrapGenerators types.String `tfsdk:"trap_generators"`
	TrapInterfaces types.String `tfsdk:"trap_interfaces"`
	TrapTarget     types.String `tfsdk:"trap_target"`
	TrapVersion    types.Int64  `tfsdk:"trap_version"`
	Vrf            types.String `tfsdk:"vrf"`
	Router         types.String `tfsdk:"router"`
}

func NewSNMPResource() resource.Resource { return &SNMPResource{} }

func (r *SNMPResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_snmp"
}

func (r *SNMPResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	reg, diags := configureRegistry(req.ProviderData)
	resp.Diagnostics.Append(diags...)
	if reg != nil {
		r.reg = reg
	}
}

func (r *SNMPResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Singleton; live-edit risks orphaning agent -- skip in acc",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Computed:      true,
				Description:   "Stable identifier (the singleton's menu path, optionally namespaced by router).",
				PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},
			"contact": schema.StringAttribute{Optional: true, Computed: true,
				Description: "Contact information",
			},
			"enabled": schema.BoolAttribute{Optional: true, Computed: true,
				Description: "Used to disable/enable SNMP service",
			},
			"engine_id": schema.StringAttribute{Optional: true, Computed: true,
				Description: "For SNMP v3, used as part of the identifier. You can configure the suffix part of the engine id using this argument. If the SNMP client is not capable to detect set engine-id value then this prefix hex has to be used 0x80003a8c04",
			},
			"engine_id_suffix": schema.StringAttribute{Optional: true, Computed: true,
				Description: "",
			},
			"location": schema.StringAttribute{Optional: true, Computed: true,
				Description: "Location information",
			},
			"src_address": schema.StringAttribute{Optional: true, Computed: true,
				Description: "Force the router to always use the same IP source address for all of the SNMP messages",
				Validators:  []validator.String{schemautil.IsIP()},
			},
			"trap_community": schema.StringAttribute{Optional: true, Computed: true,
				Description: "Which communities configured in the community menu to use when sending out the trap.",
			},
			"trap_generators": schema.StringAttribute{Optional: true, Computed: true,
				Description: "What action will generate traps: interfaces - interface changes; start-trap - SNMP server starting on the router temp-exception - send trap when temperature reached\u00a0100c (or value configured for cpu-overtemp-temperature at /system health )",
			},
			"trap_interfaces": schema.StringAttribute{Optional: true, Computed: true,
				Description: "List of interfaces that traps are going to be sent out.",
			},
			"trap_target": schema.StringAttribute{Optional: true, Computed: true,
				Description: "IP (IPv4 or IPv6) addresses of SNMP data collectors that have to receive the trap",
			},
			"trap_version": schema.Int64Attribute{Optional: true, Computed: true,
				Description: "A version of SNMP protocol to use for trap",
			},
			"vrf": schema.StringAttribute{Optional: true, Computed: true,
				Description: "Set VRF on which service is listening for incoming connections",
			},
			"router": schema.StringAttribute{Optional: true,
				Description: "Name of the router (key in provider's `routers` map). Omit to use the default.",
			},
		},
	}
}

func (r *SNMPResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan SNMPModel
	if d := req.Plan.Get(ctx, &plan); d.HasError() {
		resp.Diagnostics.Append(d...)
		return
	}
	sNMPUpsert(ctx, r.reg, &plan, &resp.Diagnostics)
	if resp.Diagnostics.HasError() {
		return
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *SNMPResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan SNMPModel
	if d := req.Plan.Get(ctx, &plan); d.HasError() {
		resp.Diagnostics.Append(d...)
		return
	}
	sNMPUpsert(ctx, r.reg, &plan, &resp.Diagnostics)
	if resp.Diagnostics.HasError() {
		return
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *SNMPResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state SNMPModel
	if d := req.State.Get(ctx, &state); d.HasError() {
		resp.Diagnostics.Append(d...)
		return
	}
	c := pickClient(r.reg, state.Router, &resp.Diagnostics)
	if c == nil {
		return
	}
	obj, err := c.GetSingleton(ctx, "/snmp")
	if err != nil {
		resp.Diagnostics.AddError("Read /snmp failed", err.Error())
		return
	}
	sNMPApply(ctx, obj, &state)
	state.ID = types.StringValue(stateIDFor("/snmp", state.Router))
	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *SNMPResource) Delete(_ context.Context, _ resource.DeleteRequest, _ *resource.DeleteResponse) {
	// Singleton menus aren't removable; just drop the state.
}

func (r *SNMPResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	// Import format: "<router>" or empty for default.
	routerName := req.ID
	if routerName == "/snmp" {
		routerName = ""
	}
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("router"), types.StringValue(routerName))...)
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("id"), types.StringValue(stateIDFor("/snmp", types.StringValue(routerName))))...)
}

func sNMPUpsert(ctx context.Context, reg *client.Registry, plan *SNMPModel, diags *diagBuf) {
	c := pickClient(reg, plan.Router, diags)
	if c == nil {
		return
	}
	body := client.Object{}
	if !(plan.Contact.IsNull() || plan.Contact.IsUnknown()) {
		body["contact"] = plan.Contact.ValueString()
	}
	if !(plan.Enabled.IsNull() || plan.Enabled.IsUnknown()) {
		body["enabled"] = client.FormatBool(plan.Enabled.ValueBool())
	}
	if !(plan.EngineIDSuffix.IsNull() || plan.EngineIDSuffix.IsUnknown()) {
		body["engine-id-suffix"] = plan.EngineIDSuffix.ValueString()
	}
	if !(plan.Location.IsNull() || plan.Location.IsUnknown()) {
		body["location"] = plan.Location.ValueString()
	}
	if !(plan.SrcAddress.IsNull() || plan.SrcAddress.IsUnknown()) {
		body["src-address"] = plan.SrcAddress.ValueString()
	}
	if !(plan.TrapCommunity.IsNull() || plan.TrapCommunity.IsUnknown()) {
		body["trap-community"] = plan.TrapCommunity.ValueString()
	}
	if !(plan.TrapGenerators.IsNull() || plan.TrapGenerators.IsUnknown()) {
		body["trap-generators"] = plan.TrapGenerators.ValueString()
	}
	if !(plan.TrapInterfaces.IsNull() || plan.TrapInterfaces.IsUnknown()) {
		body["trap-interfaces"] = plan.TrapInterfaces.ValueString()
	}
	if !(plan.TrapTarget.IsNull() || plan.TrapTarget.IsUnknown()) {
		body["trap-target"] = plan.TrapTarget.ValueString()
	}
	if !(plan.TrapVersion.IsNull() || plan.TrapVersion.IsUnknown()) {
		body["trap-version"] = client.FormatInt64(plan.TrapVersion.ValueInt64())
	}
	if !(plan.Vrf.IsNull() || plan.Vrf.IsUnknown()) {
		body["vrf"] = plan.Vrf.ValueString()
	}
	obj, err := c.SetSingleton(ctx, "/snmp", body)
	if err != nil {
		diags.AddError("Upsert /snmp failed", err.Error())
		return
	}
	sNMPApply(ctx, obj, plan)
	plan.ID = types.StringValue(stateIDFor("/snmp", plan.Router))
}

func sNMPApply(ctx context.Context, obj client.Object, m *SNMPModel) {
	_ = ctx
	if v, ok := obj["contact"]; ok {
		_ = v
		if v != "" {
			m.Contact = types.StringValue(v)
		} else {
			m.Contact = types.StringNull()
		}
	}
	if v, ok := obj["enabled"]; ok {
		_ = v
		if b, err := client.ParseBool(v); err == nil {
			m.Enabled = types.BoolValue(b)
		} else {
			m.Enabled = types.BoolNull()
		}
	}
	if v, ok := obj["engine-id"]; ok {
		_ = v
		if v != "" {
			m.EngineID = types.StringValue(v)
		} else {
			m.EngineID = types.StringNull()
		}
	}
	if v, ok := obj["engine-id-suffix"]; ok {
		_ = v
		if v != "" {
			m.EngineIDSuffix = types.StringValue(v)
		} else {
			m.EngineIDSuffix = types.StringNull()
		}
	}
	if v, ok := obj["location"]; ok {
		_ = v
		if v != "" {
			m.Location = types.StringValue(v)
		} else {
			m.Location = types.StringNull()
		}
	}
	if v, ok := obj["src-address"]; ok {
		_ = v
		if v != "" {
			m.SrcAddress = types.StringValue(v)
		} else {
			m.SrcAddress = types.StringNull()
		}
	}
	if v, ok := obj["trap-community"]; ok {
		_ = v
		if v != "" {
			m.TrapCommunity = types.StringValue(v)
		} else {
			m.TrapCommunity = types.StringNull()
		}
	}
	if v, ok := obj["trap-generators"]; ok {
		_ = v
		if v != "" {
			m.TrapGenerators = types.StringValue(v)
		} else {
			m.TrapGenerators = types.StringNull()
		}
	}
	if v, ok := obj["trap-interfaces"]; ok {
		_ = v
		if v != "" {
			m.TrapInterfaces = types.StringValue(v)
		} else {
			m.TrapInterfaces = types.StringNull()
		}
	}
	if v, ok := obj["trap-target"]; ok {
		_ = v
		if v != "" {
			m.TrapTarget = types.StringValue(v)
		} else {
			m.TrapTarget = types.StringNull()
		}
	}
	if v, ok := obj["trap-version"]; ok {
		_ = v
		if n, err := client.ParseInt64(v); err == nil {
			m.TrapVersion = types.Int64Value(n)
		} else {
			m.TrapVersion = types.Int64Null()
		}
	}
	if v, ok := obj["vrf"]; ok {
		_ = v
		if v != "" {
			m.Vrf = types.StringValue(v)
		} else {
			m.Vrf = types.StringNull()
		}
	}
}
