// Code generated by gen-provider. DO NOT EDIT.
package provider

import (
	"context"
	"fmt"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/ebogdum/terraform-provider-routeros/internal/client"
	"github.com/ebogdum/terraform-provider-routeros/internal/schemautil"
)

var (
	_ resource.Resource                = &CertificateScepServerResource{}
	_ resource.ResourceWithImportState = &CertificateScepServerResource{}
	_                                  = attr.Value(nil)
	_                                  = strings.TrimSpace
	_                                  = path.Root
)

type CertificateScepServerResource struct {
	reg *client.Registry
}

type CertificateScepServerModel struct {
	ID                types.String `tfsdk:"id"`
	CACertificate     types.String `tfsdk:"ca_certificate"`
	DaysValid         types.Int64  `tfsdk:"days_valid"`
	Disabled          types.Bool   `tfsdk:"disabled"`
	NextCACertificate types.String `tfsdk:"next_ca_certificate"`
	Path              types.String `tfsdk:"path"`
	RequestLifetime   types.String `tfsdk:"request_lifetime"`
	Router            types.String `tfsdk:"router"`
}

func NewCertificateScepServerResource() resource.Resource { return &CertificateScepServerResource{} }

func (r *CertificateScepServerResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_certificate_scep_server"
}

func (r *CertificateScepServerResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	reg, diags := configureRegistry(req.ProviderData)
	resp.Diagnostics.Append(diags...)
	if reg != nil {
		r.reg = reg
	}
	_ = fmt.Sprintf
}

func (r *CertificateScepServerResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "SCEP server references an existing CA cert. Skipped from automated acc tests.",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Computed:      true,
				Description:   "RouterOS internal .id.",
				PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},
			"ca_certificate": schema.StringAttribute{
				Optional:    true,
				Computed:    true,
				Description: "",
			},
			"days_valid": schema.Int64Attribute{
				Optional:    true,
				Computed:    true,
				Description: "",
			},
			"disabled": schema.BoolAttribute{
				Optional:    true,
				Computed:    true,
				Description: "Whether the entry is disabled.",
			},
			"next_ca_certificate": schema.StringAttribute{
				Optional:    true,
				Computed:    true,
				Description: "",
			},
			"path": schema.StringAttribute{
				Optional:    true,
				Computed:    true,
				Description: "",
			},
			"request_lifetime": schema.StringAttribute{
				Optional:      true,
				Computed:      true,
				Description:   "",
				Validators:    []validator.String{schemautil.IsDurationRouterOS()},
				PlanModifiers: []planmodifier.String{schemautil.NormalizeDuration()},
			},
			"router": schema.StringAttribute{
				Optional:    true,
				Description: "Name of the router (key in provider's `routers` map). Omit to use the default.",
			},
		},
	}
}

func (r *CertificateScepServerResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan CertificateScepServerModel
	if diags := req.Plan.Get(ctx, &plan); diags.HasError() {
		resp.Diagnostics.Append(diags...)
		return
	}
	c := pickClient(r.reg, plan.Router, &resp.Diagnostics)
	if c == nil {
		return
	}
	body := client.Object{}
	if !(plan.CACertificate.IsNull() || plan.CACertificate.IsUnknown()) {
		body["ca-certificate"] = plan.CACertificate.ValueString()
	}
	if !(plan.DaysValid.IsNull() || plan.DaysValid.IsUnknown()) {
		body["days-valid"] = client.FormatInt64(plan.DaysValid.ValueInt64())
	}
	if !(plan.Disabled.IsNull() || plan.Disabled.IsUnknown()) {
		body["disabled"] = client.FormatBool(plan.Disabled.ValueBool())
	}
	if !(plan.NextCACertificate.IsNull() || plan.NextCACertificate.IsUnknown()) {
		body["next-ca-certificate"] = plan.NextCACertificate.ValueString()
	}
	if !(plan.Path.IsNull() || plan.Path.IsUnknown()) {
		body["path"] = plan.Path.ValueString()
	}
	if !(plan.RequestLifetime.IsNull() || plan.RequestLifetime.IsUnknown()) {
		body["request-lifetime"] = plan.RequestLifetime.ValueString()
	}
	obj, err := c.Add(ctx, "/certificate/scep-server", body)
	if err != nil {
		resp.Diagnostics.AddError("Create /certificate/scep-server failed", err.Error())
		return
	}
	certificateScepServerApply(ctx, obj, &plan)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *CertificateScepServerResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state CertificateScepServerModel
	if diags := req.State.Get(ctx, &state); diags.HasError() {
		resp.Diagnostics.Append(diags...)
		return
	}
	c := pickClient(r.reg, state.Router, &resp.Diagnostics)
	if c == nil {
		return
	}
	obj, err := c.GetByID(ctx, "/certificate/scep-server", state.ID.ValueString())
	if err != nil {
		if client.IsNotFound(err) {
			resp.State.RemoveResource(ctx)
			return
		}
		resp.Diagnostics.AddError("Read /certificate/scep-server failed", err.Error())
		return
	}
	certificateScepServerApply(ctx, obj, &state)
	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *CertificateScepServerResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan, state CertificateScepServerModel
	if diags := req.Plan.Get(ctx, &plan); diags.HasError() {
		resp.Diagnostics.Append(diags...)
		return
	}
	if diags := req.State.Get(ctx, &state); diags.HasError() {
		resp.Diagnostics.Append(diags...)
		return
	}
	c := pickClient(r.reg, plan.Router, &resp.Diagnostics)
	if c == nil {
		return
	}
	body := client.Object{}
	if !plan.CACertificate.Equal(state.CACertificate) {
		body["ca-certificate"] = plan.CACertificate.ValueString()
	}
	if !plan.DaysValid.Equal(state.DaysValid) {
		body["days-valid"] = client.FormatInt64(plan.DaysValid.ValueInt64())
	}
	if !plan.Disabled.Equal(state.Disabled) {
		body["disabled"] = client.FormatBool(plan.Disabled.ValueBool())
	}
	if !plan.NextCACertificate.Equal(state.NextCACertificate) {
		body["next-ca-certificate"] = plan.NextCACertificate.ValueString()
	}
	if !plan.Path.Equal(state.Path) {
		body["path"] = plan.Path.ValueString()
	}
	if !plan.RequestLifetime.Equal(state.RequestLifetime) {
		body["request-lifetime"] = plan.RequestLifetime.ValueString()
	}
	if len(body) > 0 {
		obj, err := c.Set(ctx, "/certificate/scep-server", state.ID.ValueString(), body)
		if err != nil {
			resp.Diagnostics.AddError("Update /certificate/scep-server failed", err.Error())
			return
		}
		certificateScepServerApply(ctx, obj, &plan)
	} else {
		plan.ID = state.ID
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *CertificateScepServerResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state CertificateScepServerModel
	if diags := req.State.Get(ctx, &state); diags.HasError() {
		resp.Diagnostics.Append(diags...)
		return
	}
	c := pickClient(r.reg, state.Router, &resp.Diagnostics)
	if c == nil {
		return
	}
	if err := c.Remove(ctx, "/certificate/scep-server", state.ID.ValueString()); err != nil {
		resp.Diagnostics.AddError("Delete /certificate/scep-server failed", err.Error())
	}
}

func (r *CertificateScepServerResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	// Import formats accepted:
	//   *<id>                            -> bare RouterOS .id on the default router
	//   <router>/*<id>                   -> .id on the named router
	//   <router>/<naturalkey>            -> resolved via List + filter
	//   <naturalkey>                     -> resolved on the default router
	id := req.ID
	routerName := ""
	if i := strings.Index(id, "/"); i > 0 && !strings.HasPrefix(id, "*") {
		routerName, id = id[:i], id[i+1:]
	}
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("router"), types.StringValue(routerName))...)
	if strings.HasPrefix(id, "*") {
		resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("id"), types.StringValue(id))...)
		return
	}
	c := pickClient(r.reg, types.StringValue(routerName), &resp.Diagnostics)
	if c == nil {
		return
	}
	rows, err := certificateScepServerLookupByNaturalKey(ctx, c, id)
	if err != nil {
		resp.Diagnostics.AddError("Import lookup failed", err.Error())
		return
	}
	if len(rows) == 0 {
		resp.Diagnostics.AddError("Import not found", fmt.Sprintf("no /certificate/scep-server matches %q", id))
		return
	}
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("id"), types.StringValue(rows[0][".id"]))...)
}

// certificateScepServerLookupByNaturalKey searches for a record whose natural
// keys match id. The strategy: try every key declared in the schema overlay's
// natural_keys list (or fall back to "name") with equality matching.
func certificateScepServerLookupByNaturalKey(ctx context.Context, c *client.Client, id string) ([]client.Object, error) {
	keys := []string{}
	if len(keys) == 0 {
		keys = []string{"name"}
	}
	for _, k := range keys {
		rows, err := c.List(ctx, "/certificate/scep-server", client.WithFilter(k, id))
		if err != nil {
			return nil, err
		}
		if len(rows) > 0 {
			return rows, nil
		}
	}
	return nil, nil
}

func certificateScepServerApply(ctx context.Context, obj client.Object, m *CertificateScepServerModel) {
	_ = ctx
	m.ID = types.StringValue(obj[".id"])
	if v, ok := obj["ca-certificate"]; ok {
		_ = v
		if v != "" {
			m.CACertificate = types.StringValue(v)
		} else {
			m.CACertificate = types.StringNull()
		}
	} else {
		m.CACertificate = types.StringNull()
	}
	if v, ok := obj["days-valid"]; ok {
		_ = v
		if n, err := client.ParseInt64(v); err == nil {
			m.DaysValid = types.Int64Value(n)
		} else {
			m.DaysValid = types.Int64Null()
		}
	} else {
		m.DaysValid = types.Int64Null()
	}
	if v, ok := obj["disabled"]; ok {
		_ = v
		if b, err := client.ParseBool(v); err == nil {
			m.Disabled = types.BoolValue(b)
		} else {
			m.Disabled = types.BoolNull()
		}
	} else {
		m.Disabled = types.BoolNull()
	}
	if v, ok := obj["next-ca-certificate"]; ok {
		_ = v
		if v != "" {
			m.NextCACertificate = types.StringValue(v)
		} else {
			m.NextCACertificate = types.StringNull()
		}
	} else {
		m.NextCACertificate = types.StringNull()
	}
	if v, ok := obj["path"]; ok {
		_ = v
		if v != "" {
			m.Path = types.StringValue(v)
		} else {
			m.Path = types.StringNull()
		}
	} else {
		m.Path = types.StringNull()
	}
	if v, ok := obj["request-lifetime"]; ok {
		_ = v
		if v != "" {
			m.RequestLifetime = types.StringValue(v)
		} else {
			m.RequestLifetime = types.StringNull()
		}
	} else {
		m.RequestLifetime = types.StringNull()
	}
}
