// Code generated by gen-provider. DO NOT EDIT.
package provider

import (
	"context"
	"fmt"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/ebogdum/terraform-provider-routeros/internal/client"
)

var (
	_ resource.Resource                = &InterfaceWireguardPeersResource{}
	_ resource.ResourceWithImportState = &InterfaceWireguardPeersResource{}
	_                                  = attr.Value(nil)
	_                                  = strings.TrimSpace
	_                                  = path.Root
)

type InterfaceWireguardPeersResource struct {
	reg *client.Registry
}

type InterfaceWireguardPeersModel struct {
	ID                   types.String `tfsdk:"id"`
	AllowedAddress       types.String `tfsdk:"allowed_address"`
	ClientAddress        types.String `tfsdk:"client_address"`
	ClientAllowedAddress types.String `tfsdk:"client_allowed_address"`
	ClientDNS            types.String `tfsdk:"client_dns"`
	ClientEndpoint       types.String `tfsdk:"client_endpoint"`
	ClientKeepalive      types.String `tfsdk:"client_keepalive"`
	ClientListenPort     types.String `tfsdk:"client_listen_port"`
	Comment              types.String `tfsdk:"comment"`
	Disabled             types.Bool   `tfsdk:"disabled"`
	EndpointAddress      types.String `tfsdk:"endpoint_address"`
	EndpointPort         types.String `tfsdk:"endpoint_port"`
	Interface            types.String `tfsdk:"interface"`
	Name                 types.String `tfsdk:"name"`
	PersistentKeepalive  types.String `tfsdk:"persistent_keepalive"`
	PresharedKey         types.String `tfsdk:"preshared_key"`
	PrivateKey           types.String `tfsdk:"private_key"`
	PublicKey            types.String `tfsdk:"public_key"`
	Responder            types.String `tfsdk:"responder"`
	Router               types.String `tfsdk:"router"`
}

func NewInterfaceWireguardPeersResource() resource.Resource {
	return &InterfaceWireguardPeersResource{}
}

func (r *InterfaceWireguardPeersResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_interface_wireguard_peers"
}

func (r *InterfaceWireguardPeersResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	reg, diags := configureRegistry(req.ProviderData)
	resp.Diagnostics.Append(diags...)
	if reg != nil {
		r.reg = reg
	}
	_ = fmt.Sprintf
}

func (r *InterfaceWireguardPeersResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Peer attached to a /interface/wireguard interface. Set the `interface`\nattribute to an existing WireGuard interface name.\n",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Computed:      true,
				Description:   "RouterOS internal .id.",
				PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},
			"allowed_address": schema.StringAttribute{
				Optional:    true,
				Computed:    true,
				Description: "",
			},
			"client_address": schema.StringAttribute{
				Optional:    true,
				Computed:    true,
				Description: "",
			},
			"client_allowed_address": schema.StringAttribute{
				Optional:    true,
				Computed:    true,
				Description: "",
			},
			"client_dns": schema.StringAttribute{
				Optional:    true,
				Computed:    true,
				Description: "",
			},
			"client_endpoint": schema.StringAttribute{
				Optional:    true,
				Computed:    true,
				Description: "",
			},
			"client_keepalive": schema.StringAttribute{
				Optional:    true,
				Computed:    true,
				Description: "",
			},
			"client_listen_port": schema.StringAttribute{
				Optional:    true,
				Computed:    true,
				Description: "",
			},
			"comment": schema.StringAttribute{
				Optional:    true,
				Computed:    true,
				Description: "Free-form comment.",
			},
			"disabled": schema.BoolAttribute{
				Optional:    true,
				Computed:    true,
				Description: "Whether the entry is disabled.",
			},
			"endpoint_address": schema.StringAttribute{
				Optional:    true,
				Computed:    true,
				Description: "",
			},
			"endpoint_port": schema.StringAttribute{
				Optional:    true,
				Computed:    true,
				Description: "",
			},
			"interface": schema.StringAttribute{
				Optional:    true,
				Computed:    true,
				Description: "",
			},
			"name": schema.StringAttribute{
				Optional:    true,
				Computed:    true,
				Description: "",
			},
			"persistent_keepalive": schema.StringAttribute{
				Optional:    true,
				Computed:    true,
				Description: "",
			},
			"preshared_key": schema.StringAttribute{
				Optional:    true,
				Computed:    true,
				Sensitive:   true,
				Description: "",
			},
			"private_key": schema.StringAttribute{
				Optional:    true,
				Computed:    true,
				Sensitive:   true,
				Description: "",
			},
			"public_key": schema.StringAttribute{
				Optional:    true,
				Computed:    true,
				Description: "",
			},
			"responder": schema.StringAttribute{
				Optional:    true,
				Computed:    true,
				Description: "",
			},
			"router": schema.StringAttribute{
				Optional:    true,
				Description: "Name of the router (key in provider's `routers` map). Omit to use the default.",
			},
		},
	}
}

func (r *InterfaceWireguardPeersResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan InterfaceWireguardPeersModel
	if diags := req.Plan.Get(ctx, &plan); diags.HasError() {
		resp.Diagnostics.Append(diags...)
		return
	}
	c := pickClient(r.reg, plan.Router, &resp.Diagnostics)
	if c == nil {
		return
	}
	body := client.Object{}
	if !(plan.AllowedAddress.IsNull() || plan.AllowedAddress.IsUnknown()) {
		body["allowed-address"] = plan.AllowedAddress.ValueString()
	}
	if !(plan.ClientAddress.IsNull() || plan.ClientAddress.IsUnknown()) {
		body["client-address"] = plan.ClientAddress.ValueString()
	}
	if !(plan.ClientAllowedAddress.IsNull() || plan.ClientAllowedAddress.IsUnknown()) {
		body["client-allowed-address"] = plan.ClientAllowedAddress.ValueString()
	}
	if !(plan.ClientDNS.IsNull() || plan.ClientDNS.IsUnknown()) {
		body["client-dns"] = plan.ClientDNS.ValueString()
	}
	if !(plan.ClientEndpoint.IsNull() || plan.ClientEndpoint.IsUnknown()) {
		body["client-endpoint"] = plan.ClientEndpoint.ValueString()
	}
	if !(plan.ClientKeepalive.IsNull() || plan.ClientKeepalive.IsUnknown()) {
		body["client-keepalive"] = plan.ClientKeepalive.ValueString()
	}
	if !(plan.ClientListenPort.IsNull() || plan.ClientListenPort.IsUnknown()) {
		body["client-listen-port"] = plan.ClientListenPort.ValueString()
	}
	if !(plan.Comment.IsNull() || plan.Comment.IsUnknown()) {
		body["comment"] = plan.Comment.ValueString()
	}
	if !(plan.Disabled.IsNull() || plan.Disabled.IsUnknown()) {
		body["disabled"] = client.FormatBool(plan.Disabled.ValueBool())
	}
	if !(plan.EndpointAddress.IsNull() || plan.EndpointAddress.IsUnknown()) {
		body["endpoint-address"] = plan.EndpointAddress.ValueString()
	}
	if !(plan.EndpointPort.IsNull() || plan.EndpointPort.IsUnknown()) {
		body["endpoint-port"] = plan.EndpointPort.ValueString()
	}
	if !(plan.Interface.IsNull() || plan.Interface.IsUnknown()) {
		body["interface"] = plan.Interface.ValueString()
	}
	if !(plan.Name.IsNull() || plan.Name.IsUnknown()) {
		body["name"] = plan.Name.ValueString()
	}
	if !(plan.PersistentKeepalive.IsNull() || plan.PersistentKeepalive.IsUnknown()) {
		body["persistent-keepalive"] = plan.PersistentKeepalive.ValueString()
	}
	if !(plan.PresharedKey.IsNull() || plan.PresharedKey.IsUnknown()) {
		body["preshared-key"] = plan.PresharedKey.ValueString()
	}
	if !(plan.PrivateKey.IsNull() || plan.PrivateKey.IsUnknown()) {
		body["private-key"] = plan.PrivateKey.ValueString()
	}
	if !(plan.PublicKey.IsNull() || plan.PublicKey.IsUnknown()) {
		body["public-key"] = plan.PublicKey.ValueString()
	}
	if !(plan.Responder.IsNull() || plan.Responder.IsUnknown()) {
		body["responder"] = plan.Responder.ValueString()
	}
	obj, err := c.Add(ctx, "/interface/wireguard/peers", body)
	if err != nil {
		resp.Diagnostics.AddError("Create /interface/wireguard/peers failed", err.Error())
		return
	}
	interfaceWireguardPeersApply(ctx, obj, &plan)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *InterfaceWireguardPeersResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state InterfaceWireguardPeersModel
	if diags := req.State.Get(ctx, &state); diags.HasError() {
		resp.Diagnostics.Append(diags...)
		return
	}
	c := pickClient(r.reg, state.Router, &resp.Diagnostics)
	if c == nil {
		return
	}
	obj, err := c.GetByID(ctx, "/interface/wireguard/peers", state.ID.ValueString())
	if err != nil {
		if client.IsNotFound(err) {
			resp.State.RemoveResource(ctx)
			return
		}
		resp.Diagnostics.AddError("Read /interface/wireguard/peers failed", err.Error())
		return
	}
	interfaceWireguardPeersApply(ctx, obj, &state)
	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *InterfaceWireguardPeersResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan, state InterfaceWireguardPeersModel
	if diags := req.Plan.Get(ctx, &plan); diags.HasError() {
		resp.Diagnostics.Append(diags...)
		return
	}
	if diags := req.State.Get(ctx, &state); diags.HasError() {
		resp.Diagnostics.Append(diags...)
		return
	}
	c := pickClient(r.reg, plan.Router, &resp.Diagnostics)
	if c == nil {
		return
	}
	body := client.Object{}
	if !plan.AllowedAddress.Equal(state.AllowedAddress) {
		body["allowed-address"] = plan.AllowedAddress.ValueString()
	}
	if !plan.ClientAddress.Equal(state.ClientAddress) {
		body["client-address"] = plan.ClientAddress.ValueString()
	}
	if !plan.ClientAllowedAddress.Equal(state.ClientAllowedAddress) {
		body["client-allowed-address"] = plan.ClientAllowedAddress.ValueString()
	}
	if !plan.ClientDNS.Equal(state.ClientDNS) {
		body["client-dns"] = plan.ClientDNS.ValueString()
	}
	if !plan.ClientEndpoint.Equal(state.ClientEndpoint) {
		body["client-endpoint"] = plan.ClientEndpoint.ValueString()
	}
	if !plan.ClientKeepalive.Equal(state.ClientKeepalive) {
		body["client-keepalive"] = plan.ClientKeepalive.ValueString()
	}
	if !plan.ClientListenPort.Equal(state.ClientListenPort) {
		body["client-listen-port"] = plan.ClientListenPort.ValueString()
	}
	if !plan.Comment.Equal(state.Comment) {
		body["comment"] = plan.Comment.ValueString()
	}
	if !plan.Disabled.Equal(state.Disabled) {
		body["disabled"] = client.FormatBool(plan.Disabled.ValueBool())
	}
	if !plan.EndpointAddress.Equal(state.EndpointAddress) {
		body["endpoint-address"] = plan.EndpointAddress.ValueString()
	}
	if !plan.EndpointPort.Equal(state.EndpointPort) {
		body["endpoint-port"] = plan.EndpointPort.ValueString()
	}
	if !plan.Interface.Equal(state.Interface) {
		body["interface"] = plan.Interface.ValueString()
	}
	if !plan.Name.Equal(state.Name) {
		body["name"] = plan.Name.ValueString()
	}
	if !plan.PersistentKeepalive.Equal(state.PersistentKeepalive) {
		body["persistent-keepalive"] = plan.PersistentKeepalive.ValueString()
	}
	if !plan.PresharedKey.Equal(state.PresharedKey) {
		body["preshared-key"] = plan.PresharedKey.ValueString()
	}
	if !plan.PrivateKey.Equal(state.PrivateKey) {
		body["private-key"] = plan.PrivateKey.ValueString()
	}
	if !plan.PublicKey.Equal(state.PublicKey) {
		body["public-key"] = plan.PublicKey.ValueString()
	}
	if !plan.Responder.Equal(state.Responder) {
		body["responder"] = plan.Responder.ValueString()
	}
	if len(body) > 0 {
		obj, err := c.Set(ctx, "/interface/wireguard/peers", state.ID.ValueString(), body)
		if err != nil {
			resp.Diagnostics.AddError("Update /interface/wireguard/peers failed", err.Error())
			return
		}
		interfaceWireguardPeersApply(ctx, obj, &plan)
	} else {
		plan.ID = state.ID
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *InterfaceWireguardPeersResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state InterfaceWireguardPeersModel
	if diags := req.State.Get(ctx, &state); diags.HasError() {
		resp.Diagnostics.Append(diags...)
		return
	}
	c := pickClient(r.reg, state.Router, &resp.Diagnostics)
	if c == nil {
		return
	}
	if err := c.Remove(ctx, "/interface/wireguard/peers", state.ID.ValueString()); err != nil {
		resp.Diagnostics.AddError("Delete /interface/wireguard/peers failed", err.Error())
	}
}

func (r *InterfaceWireguardPeersResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	// Import formats accepted:
	//   *<id>                            -> bare RouterOS .id on the default router
	//   <router>/*<id>                   -> .id on the named router
	//   <router>/<naturalkey>            -> resolved via List + filter
	//   <naturalkey>                     -> resolved on the default router
	id := req.ID
	routerName := ""
	if i := strings.Index(id, "/"); i > 0 && !strings.HasPrefix(id, "*") {
		routerName, id = id[:i], id[i+1:]
	}
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("router"), types.StringValue(routerName))...)
	if strings.HasPrefix(id, "*") {
		resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("id"), types.StringValue(id))...)
		return
	}
	c := pickClient(r.reg, types.StringValue(routerName), &resp.Diagnostics)
	if c == nil {
		return
	}
	rows, err := interfaceWireguardPeersLookupByNaturalKey(ctx, c, id)
	if err != nil {
		resp.Diagnostics.AddError("Import lookup failed", err.Error())
		return
	}
	if len(rows) == 0 {
		resp.Diagnostics.AddError("Import not found", fmt.Sprintf("no /interface/wireguard/peers matches %q", id))
		return
	}
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("id"), types.StringValue(rows[0][".id"]))...)
}

// interfaceWireguardPeersLookupByNaturalKey searches for a record whose natural
// keys match id. The strategy: try every key declared in the schema overlay's
// natural_keys list (or fall back to "name") with equality matching.
func interfaceWireguardPeersLookupByNaturalKey(ctx context.Context, c *client.Client, id string) ([]client.Object, error) {
	keys := []string{}
	if len(keys) == 0 {
		keys = []string{"name"}
	}
	for _, k := range keys {
		rows, err := c.List(ctx, "/interface/wireguard/peers", client.WithFilter(k, id))
		if err != nil {
			return nil, err
		}
		if len(rows) > 0 {
			return rows, nil
		}
	}
	return nil, nil
}

func interfaceWireguardPeersApply(ctx context.Context, obj client.Object, m *InterfaceWireguardPeersModel) {
	_ = ctx
	m.ID = types.StringValue(obj[".id"])
	if v, ok := obj["allowed-address"]; ok {
		_ = v
		if v != "" {
			m.AllowedAddress = types.StringValue(v)
		} else {
			m.AllowedAddress = types.StringNull()
		}
	} else {
		m.AllowedAddress = types.StringNull()
	}
	if v, ok := obj["client-address"]; ok {
		_ = v
		if v != "" {
			m.ClientAddress = types.StringValue(v)
		} else {
			m.ClientAddress = types.StringNull()
		}
	} else {
		m.ClientAddress = types.StringNull()
	}
	if v, ok := obj["client-allowed-address"]; ok {
		_ = v
		if v != "" {
			m.ClientAllowedAddress = types.StringValue(v)
		} else {
			m.ClientAllowedAddress = types.StringNull()
		}
	} else {
		m.ClientAllowedAddress = types.StringNull()
	}
	if v, ok := obj["client-dns"]; ok {
		_ = v
		if v != "" {
			m.ClientDNS = types.StringValue(v)
		} else {
			m.ClientDNS = types.StringNull()
		}
	} else {
		m.ClientDNS = types.StringNull()
	}
	if v, ok := obj["client-endpoint"]; ok {
		_ = v
		if v != "" {
			m.ClientEndpoint = types.StringValue(v)
		} else {
			m.ClientEndpoint = types.StringNull()
		}
	} else {
		m.ClientEndpoint = types.StringNull()
	}
	if v, ok := obj["client-keepalive"]; ok {
		_ = v
		if v != "" {
			m.ClientKeepalive = types.StringValue(v)
		} else {
			m.ClientKeepalive = types.StringNull()
		}
	} else {
		m.ClientKeepalive = types.StringNull()
	}
	if v, ok := obj["client-listen-port"]; ok {
		_ = v
		if v != "" {
			m.ClientListenPort = types.StringValue(v)
		} else {
			m.ClientListenPort = types.StringNull()
		}
	} else {
		m.ClientListenPort = types.StringNull()
	}
	if v, ok := obj["comment"]; ok {
		_ = v
		if v != "" {
			m.Comment = types.StringValue(v)
		} else {
			m.Comment = types.StringNull()
		}
	} else {
		m.Comment = types.StringNull()
	}
	if v, ok := obj["disabled"]; ok {
		_ = v
		if b, err := client.ParseBool(v); err == nil {
			m.Disabled = types.BoolValue(b)
		} else {
			m.Disabled = types.BoolNull()
		}
	} else {
		m.Disabled = types.BoolNull()
	}
	if v, ok := obj["endpoint-address"]; ok {
		_ = v
		if v != "" {
			m.EndpointAddress = types.StringValue(v)
		} else {
			m.EndpointAddress = types.StringNull()
		}
	} else {
		m.EndpointAddress = types.StringNull()
	}
	if v, ok := obj["endpoint-port"]; ok {
		_ = v
		if v != "" {
			m.EndpointPort = types.StringValue(v)
		} else {
			m.EndpointPort = types.StringNull()
		}
	} else {
		m.EndpointPort = types.StringNull()
	}
	if v, ok := obj["interface"]; ok {
		_ = v
		if v != "" {
			m.Interface = types.StringValue(v)
		} else {
			m.Interface = types.StringNull()
		}
	} else {
		m.Interface = types.StringNull()
	}
	if v, ok := obj["name"]; ok {
		_ = v
		if v != "" {
			m.Name = types.StringValue(v)
		} else {
			m.Name = types.StringNull()
		}
	} else {
		m.Name = types.StringNull()
	}
	if v, ok := obj["persistent-keepalive"]; ok {
		_ = v
		if v != "" {
			m.PersistentKeepalive = types.StringValue(v)
		} else {
			m.PersistentKeepalive = types.StringNull()
		}
	} else {
		m.PersistentKeepalive = types.StringNull()
	}
	// Sensitive: RouterOS scrubs the value on read. If the server returned
	// a value, decode it. Otherwise the plan value (user input) is what's
	// in m.PresharedKey already -- but if the user left it unset, resolve
	// the unknown to null so the framework accepts the state.
	if v, ok := obj["preshared-key"]; ok && v != "" {
		_ = v
		if v != "" {
			m.PresharedKey = types.StringValue(v)
		} else {
			m.PresharedKey = types.StringNull()
		}
	} else if m.PresharedKey.IsUnknown() {
		m.PresharedKey = types.StringNull()
	}
	// Sensitive: RouterOS scrubs the value on read. If the server returned
	// a value, decode it. Otherwise the plan value (user input) is what's
	// in m.PrivateKey already -- but if the user left it unset, resolve
	// the unknown to null so the framework accepts the state.
	if v, ok := obj["private-key"]; ok && v != "" {
		_ = v
		if v != "" {
			m.PrivateKey = types.StringValue(v)
		} else {
			m.PrivateKey = types.StringNull()
		}
	} else if m.PrivateKey.IsUnknown() {
		m.PrivateKey = types.StringNull()
	}
	if v, ok := obj["public-key"]; ok {
		_ = v
		if v != "" {
			m.PublicKey = types.StringValue(v)
		} else {
			m.PublicKey = types.StringNull()
		}
	} else {
		m.PublicKey = types.StringNull()
	}
	if v, ok := obj["responder"]; ok {
		_ = v
		if v != "" {
			m.Responder = types.StringValue(v)
		} else {
			m.Responder = types.StringNull()
		}
	} else {
		m.Responder = types.StringNull()
	}
}
